- .rubocop.yml
- app/controllers/downloads_controller.rb
- app/jobs/demo_get_download_files_job.rb
- app/jobs/demo_get_download_manifest_job.rb
- app/models/download.rb
- app/views/downloads/_confirm.html.erb
- app/views/downloads/_progress.html.erb
- app/views/downloads/new.html.erb
- spec/features/download_spec.rb
> More redesign tweaks, Add demo data

- config/application.rb
- spec/services/download_documents_spec.rb
Worker job will not be started in rails root dir
> Use an absolute path for downloads_dir

- config/initializers/omniauth.rb
> Don't hardcode the saml entity id

- app/controllers/health_checks_controller.rb
- config/environments/production.rb
- config/routes.rb
> Add health-check path that is exempt from force_ssl

- vendor/gems/connect_vbms/src/vbms/client.rb
- vendor/gems/connect_vbms/src/vbms/common.rb
- vendor/gems/connect_vbms/src/vbms/responses/document_with_content.rb
From:
https://github.com/department-of-veterans-affairs/connect_vbms/pull/118
> Merge in connect_vbms optimizations

- app/views/layouts/application.html.erb
- config/initializers/build_version.rb
> Display build-version and date

- Gemfile
> force master branch of bgs gem

- Gemfile.lock
- app/jobs/demo_get_download_manifest_job.rb
- app/models/document.rb
- app/services/download_documents.rb
- db/migrate/20160602141549_rename_filename_to_vbms_filename_on_documents.rb
- db/schema.rb
- spec/features/download_spec.rb
- spec/models/document_spec.rb
- spec/services/download_documents_spec.rb
> Use mime type to name file downloads, don't trust the vbms filename

- config/initializers/logger.rb
> add rollover logging, log username as tag

- Gemfile
- Gemfile.lock
- config/database.yml
> Use PostgreSQL

- config/environments/production.rb
> Remove '?' from s3_enabled assignment

- Gemfile
- Gemfile.lock
- app/models/document.rb
- spec/services/download_documents_spec.rb
> Use zaru gem to sanitize filename

- app/assets/stylesheets/_caseflow.scss
- app/views/layouts/application.html.erb
> Click-able logo :)

- app/services/download_documents.rb
- spec/services/download_documents_spec.rb
> Change numbering scheme on filename downloads

- config/initializers/logger.rb
> make sure log_formatter isn't obliterated when creating new logger

- app/models/download.rb
- app/views/downloads/_progress.html.erb
- db/schema.rb
- spec/models/download_spec.rb
> Add time estimates to download progress

- app/views/downloads/_confirm.html.erb
- app/views/downloads/_progress.html.erb
> Use correct label for Receipt Date

- app/assets/stylesheets/_caseflow.scss
- app/assets/stylesheets/_download.scss
- app/controllers/downloads_controller.rb
- app/helpers/application_helper.rb
- app/jobs/demo_get_download_manifest_job.rb
- app/models/download.rb
- app/services/download_documents.rb
- app/views/downloads/new.html.erb
- app/views/downloads/show.html.erb
- db/migrate/20160708132011_add_veteran_name_to_downloads.rb
- db/schema.rb
- lib/fakes/bgs_service.rb
- spec/features/download_spec.rb
- spec/models/download_spec.rb
- spec/services/download_documents_spec.rb
fixes #142 
fixes #141 
fixes #144 
fixes #120 
fixes #135
> Redesign stories

- app/controllers/downloads_controller.rb
- app/models/download.rb
- app/services/bgs_service.rb
- app/views/downloads/new.html.erb
- spec/features/download_spec.rb
> Correctly detect cases that aren't found

- app/models/download.rb
- app/services/download_documents.rb
- config/initializers/date_formats.rb
- spec/features/download_spec.rb
- spec/models/download_spec.rb
- spec/services/download_documents_spec.rb
> Make a more descriptive filename for zip file

- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
requires addition of SSO_HOST environment variable to deployment
ie:
```
export SSO_HOST="https://cf.preprod.ds.va.gov"
```
> Modify SSO logic to reroute auth request through SSO domain

- config/initializers/logger.rb
> log user's id and email on each line (not entire user hash)

- app/models/document.rb
- spec/models/document_spec.rb
> Default vbms_filename to empty string

- app/assets/stylesheets/_main.scss
- app/controllers/downloads_controller.rb
- app/jobs/demo_get_download_manifest_job.rb
- app/models/download.rb
- app/views/downloads/_progress.html.erb
- config/routes.rb
- spec/features/download_spec.rb
- spec/models/download_spec.rb
> Add retry button to error page

- app/controllers/downloads_controller.rb
- app/models/search.rb
- app/views/downloads/new.html.erb
- db/migrate/20160726190352_create_searches.rb
- db/schema.rb
- spec/features/download_spec.rb
- spec/models/search_spec.rb
> Record searches, factor logic into search object

- config/initializers/sidekiq.rb
No cron jobs seem to be running in prod... I think this is the reason.
fixes #197
> Add absolute path to sidekiq cron directory

- app/models/search.rb
- spec/models/search_spec.rb
> Only check active downloads for cached searches

- app/jobs/calculate_stats_job.rb
> Fix stats job syntax error

- app/views/downloads/_confirm.html.erb
- app/views/downloads/_progress.html.erb
- app/views/downloads/new.html.erb
- spec/features/download_spec.rb
> Update copy to be more usable

- Gemfile
- Gemfile.lock
- app/controllers/stats_controller.rb
- app/views/stats/show.html.erb
- spec/features/dashboard_spec.rb
- spec/models/stats_spec.rb
This includes:
* Stats are now calculated for the New York timezone
* Fix for the Firefox mouseover bug (#222)
> Pull latest stats changes from Commons

- Gemfile
- Gemfile.lock
See https://github.com/department-of-veterans-affairs/caseflow-commons/issues/7
> bump commons->b743c64

- README.md
Adds some further setup instructions.
Tested and local env doesn't run if i don't have PG and Redis running in Terminal.
> readme instructs you to install & run  postgres, redis

- README.md
Instruct devs to use brew info to run services on startup.
h/t @shanear
> instructions to run redis & pg on startup

- README.md
This PR updates the README to include information for running migrations against test & development DB, and steps for running the test suite.
Testing:
- Loaded local README, looks good:
- Ran the new steps provided in the readme and they work
> Update README with migration & testing steps

- app/views/downloads/_progress.html.erb
- Update copy when eX is retrieving documents
Fixes #260 
Testing:
Verified manually in browser, now looks like
> Update retrieving page copy

- app/controllers/health_checks_controller.rb
- spec/requests/health_checks_spec.rb
> Add json info blob to the health check

- Jenkinsfile
This will reduce the amount of redundant Jenkinsfile pipeline code among the projects.
See also department-of-veterans-affairs/appeals-deployment#169
This is the eX version of https://github.com/department-of-veterans-affairs/caseflow-certification/pull/358
> Reduced the Jenkinsfile to the boilerplate

- Jenkinsfile
In support of https://github.com/department-of-veterans-affairs/appeals-deployment/pull/170
Do not merge until above PR has been merged
> Update Jenkinsfile with new paths 

- Jenkinsfile
See also failed attempts in #278 and #273 
Successful changes should be proted over to https://github.com/department-of-veterans-affairs/caseflow-certification/pull/367
> Use correct relative paths in Jenkinsfile

- app/controllers/application_controller.rb
untested, need sentry access and the sentry DSN so i can see these coming through
@shanear @orischwartz — are you able to set me up with those?
> logs user in sentry

- Gemfile
- Gemfile.lock
- config/secrets.yml
Changes are the following:
- Allow Redis URL to be overwritten
- Added sqlite3 gem dependency
> Preparing efolder for dev environment

- app/views/downloads/new.html.erb
> Fixed a minor typo

- app/views/sessions/unauthorized.html.erb
- spec/features/dashboard_spec.rb
Hi,
As per issue #29 I modified the message so it fits the styling of the other error messages. I also fixed a test in dashboard_spec.rb since the wording changed. PTAL @KHarshawat @lakohl @shanear
> fixing issue #29 for starter task

- app/views/sessions/unauthorized.html.erb
@lakohl @KHarshawat I fixed the formatting...can you please take a look?
> v2 of issue #29

- app/controllers/application_controller.rb
- app/models/download.rb
- app/services/bgs_service.rb
- spec/services/bgs_service_spec.rb
Fakes::BGSService is still a singleton, need to assess whether
we want to change that in a follow up tech-improvement issue.
#314
> Make `BGSService` not a singleton.

- app/models/download.rb
It ain't pretty, but it works for now, following up on a better
long term solution.
> Fix threading issue with User and BGSService

- app/views/downloads/_progress.html.erb
PTAL @KHarshawat @shanear 
Screenshot from local
> remove <br> from success message #292

- app/views/downloads/new.html.erb
> move error above efolder header

- Gemfile
- Gemfile.lock
- config/initializers/logger.rb
This PR sends logs to stdout. 
Fixes #190
> Log updates

- Gemfile
This PR fixes the logging to not spam the unit tests
> Logging only goes to stdout in prod, dev, and staging

- Gemfile
- Gemfile.lock
- app/models/download.rb
- app/models/search.rb
- app/models/user.rb
- db/migrate/20161214165833_add_email_to_searches.rb
- db/schema.rb
- lib/fakes/test_auth_strategy.rb
- spec/features/dashboard_spec.rb
- spec/features/download_spec.rb
- spec/models/document_spec.rb
- spec/models/download_spec.rb
- spec/models/stats_spec.rb
- spec/rails_helper.rb
- spec/services/download_documents_spec.rb
- spec/support/database_cleaner.rb
1. Add email to the `searches` table
2. Add `database_cleaner` to rspec
connected #301 
Note: I think it would be better to create a follow up issue and create a `users` table.
> Add user's Email to the `searches` table

- app/controllers/downloads_controller.rb
- app/models/download.rb
- app/models/search.rb
- app/models/user.rb
- spec/features/dashboard_spec.rb
- spec/features/download_spec.rb
- spec/models/download_spec.rb
- spec/models/search_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
Connects #326
This is PR 2 to replace user_id with css_id everywhere in the code.
> Remove all refences to user_id in the code replacing them with css_id

- app/models/download.rb
- app/models/search.rb
- app/models/user.rb
- db/migrate/20161222194523_create_users.rb
- db/schema.rb
- spec/features/download_spec.rb
- spec/models/user_spec.rb
- spec/rails_helper.rb
This is the 4th PR:
* Add the users table.
* Add user_id column back to both searches and downloads as an integer
* Begin writing new users to the users table, and adding the appropriate user_id value to new searches and downloads.
* Migrate all css_id and station_id on downloads and searches to the users table, and add the appropriate user_id to each row.
connected #325
> Add users table

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- config/initializers/assets.rb
> adding new favicon

- app/services/download_documents.rb
- spec/services/download_documents_spec.rb
connects https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/346
> Update download updated_at on file download success/fail

- app/services/download_documents.rb
- config/sidekiq_cron.yml
- spec/services/download_documents_spec.rb
> Cleanup extra files after a package is zipped up

- Gemfile
- Gemfile.lock
- app/middleware/metrics_auth.rb
- config.ru
- config/environments/development.rb
Adds prometheus client gem and /metrics route protected by password.
Testing: visited /metrics, entered passwords in dev config, saw route.
> Enables prometheus /metrics route.

- .travis.yml
Use --deployment with bundle install in Travis
#359
> Use --deployment with bundle install in Travis

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- db/schema.rb
References https://github.com/department-of-veterans-affairs/caseflow-commons/issues/13
This is a special div to add a border before the sign out button which has margins around the border.
> Marian add dropdown border

- app/views/downloads/new.html.erb
Referencing issue https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/329
Screenshot:
> add right chevron next to view results

- Gemfile
- Gemfile.lock
> Use updated caseflow-commons (addresses caseflow-efolder/issues/328)

- Gemfile
- Gemfile.lock
- app/views/help/show.html.erb
References issue https://github.com/department-of-veterans-affairs/caseflow-commons/issues/25
> Marian faq

- app/models/document.rb
- spec/models/document_spec.rb
Connected to #371 
Whenever file_name is longer than 100, we crop type_name to adjust
Added method for cropping and rspec tests for all length scenarios.
> Nemo/Added a function for cropping type_name. Added rspec tests.

- app/models/user.rb
> Revert PR 339

- Gemfile
- Gemfile.lock
Connects https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/327
> Use updated gem with fix to spinning logo

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
Connects https://github.com/department-of-veterans-affairs/caseflow-commons/issues/22
> Adjusted app layout to account for sticky footer CSS in commons

- config/initializers/assets.rb
Same as https://github.com/department-of-veterans-affairs/caseflow/pull/1048
> Fix font precompile path for new USWDS

- Gemfile.lock
- config/initializers/sidekiq.rb
This fixes:
Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)
> Nemo/Changed Sidekiq configuration for redis to redis_url_sidekiq

- app/controllers/application_controller.rb
- app/views/application/out_of_service.html.erb
- spec/features/out_of_service_spec.rb
- spec/rails_helper.rb
Connects to #312 
This is the exact same feature we did for Certification. See https://github.com/department-of-veterans-affairs/caseflow/pull/943
> Nemo/Added method check and landing page. Added spec test.

- app/views/help/show.html.erb
Edited FAQ question number 16 to address question concerning mismatch between downloaded files and files displayed in VBMS.
> File download mismatch

- Gemfile
- Gemfile.lock
Solves https://github.com/department-of-veterans-affairs/caseflow-commons/issues/66
> Use commons gem with checkboxes/radios block text

- db/migrate/20170316204433_add_type_id_to_documents.rb
- db/schema.rb
Step1 to rename doc_type to type_id.
> Add type_id to documents

- Gemfile
- Gemfile.lock
Need Redis Namespace for FeatureToggle
> Add redis namespace

- Gemfile
- Gemfile.lock
- Update caseflow-commons gem ref to pull in logger timestamp bug fix
Testing:
> Update caseflow-commons gem ref

- Jenkinsfile
this will collect the latest tag and pass it to the common pipeline for prod deployments
connects [QA #49](https://github.com/department-of-veterans-affairs/appeals-qa/issues/49)
> copy from caseflow

- app/controllers/downloads_controller.rb
> Nemo/Added logging for record_not_found.

- app/models/download.rb
- db/migrate/20170327122224_migrate_doc_type_to_type_id.rb
- db/schema.rb
Reverts department-of-veterans-affairs/caseflow-efolder#437
> Revert "Rename doc_type to type_id in documents step 3"

- db/migrate/20170407164842_migrate_doc_type_to_type_id.rb
- db/schema.rb
> Write migration using raw SQL

- app/models/document.rb
- app/services/download_documents.rb
- spec/features/download_spec.rb
- spec/models/document_spec.rb
- spec/services/download_documents_spec.rb
> Remove read/write from doc_type

- db/migrate/20170411183040_remove_doc_type_from_documents.rb
- db/schema.rb
> Create migration to remove doc_type

- app/views/downloads/new.html.erb
We have multiple "super test users" per station (CASEFLOW_283, CASEFLOW_397, etc), so let's allow them all to go crazy
https://github.com/department-of-veterans-affairs/appeals-qa/blob/master/TestData/LOGINS.md
> include Caseflow users

- app/views/downloads/new.html.erb
- db/migrate/20170425111923_split_documents_status_created_at_index.rb
- db/schema.rb
- spec/features/download_spec.rb
> split index

- config/environments/development.rb
- config/environments/test.rb
- config/routes.rb
Adds sidekiq UI for helpful debugging & requeueing of jobs
See related caseflow PR: https://github.com/department-of-veterans-affairs/caseflow/pull/1815
> Add Sidkiq UI behind basic auth

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/views/stats/show.html.erb
- spec/features/dashboard_spec.rb
Connects https://github.com/department-of-veterans-affairs/caseflow/issues/1099
> Style guide tweaks to eFolder stats page

- config/environments/demo.rb
Connects https://github.com/department-of-veterans-affairs/appeals-deployment/issues/663
I made a change that sets RAILS_ENV based on deploy environment, so the rake tasks need to be configured to be able to handle that.
This will just compile assets in production mode for `demo` RAILS_ENV.
In the future, this file can be edited to change that based on our needs
> efolder needs to be able to handle RAILS_ENV=demo

- app/controllers/downloads_controller.rb
- app/views/downloads/_confirm.html.erb
- app/views/downloads/_progress.html.erb
- app/views/downloads/new.html.erb
Updates the copy on eFolder Express to introduce the user to new features.
Connects #500
> Change copy to show new VVA features

- app/controllers/downloads_controller.rb
- app/jobs/download_files_job.rb
- app/jobs/download_manifest_job.rb
- app/jobs/fakes/download_files_job.rb
- app/jobs/fakes/download_manifest_job.rb
- app/jobs/restart_stalled_downloads_job.rb
- app/models/download.rb
- spec/features/download_spec.rb
- spec/jobs/download_manifest_job_spec.rb
- spec/models/download_spec.rb
- spec/models/search_spec.rb
Testing:
1. Tested Demo jobs locally
2. Tested real jobs locally pointed to UAT
> Re-factor sidekiq job names to follow our contention

- Gemfile
- Gemfile.lock
connects https://github.com/department-of-veterans-affairs/caseflow/issues/2407
Same deal.
> update commons for new logger

- app/controllers/downloads_controller.rb
- app/jobs/download_manifest_job.rb
- app/views/downloads/_confirm.html.erb
- app/views/downloads/_progress.html.erb
- app/views/downloads/new.html.erb
- spec/features/download_spec.rb
Request came in to enable user based access to the VVA feature.
connects #529 
Note: VVA is enabled on Demo, Test and Dev by default.
> Implement user based access to the VVA feature

- app/models/download.rb
- spec/models/download_spec.rb
> Don't force last 4 ssn to be filled out

- app/services/external_api/bgs_service.rb
- app/services/external_api/vva_service.rb
> Improve VVA logging for prometheus

- app/controllers/api/v1/documents_controller.rb
- app/models/document.rb
- app/models/fetcher.rb
- app/services/download_documents.rb
- spec/models/document_spec.rb
- spec/models/fetcher_spec.rb
- spec/services/download_documents_spec.rb
Connects: #582
We will remove the old name code in #583
> Change S3 name

- app/assets/stylesheets/_coachmarks.scss
> change padding to margin to fix underline

- app/assets/javascripts/application/vva_tour.js
- app/views/downloads/_user_header.html.erb
> VVA new coachmark

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/application_controller.rb
- app/controllers/application_controller.rb
- app/models/user.rb
- spec/features/dashboard_spec.rb
- spec/rails_helper.rb
> Nemo/Added Functions and modified spec tests.

- lib/fakes/bgs_service.rb
- spec/features/download_spec.rb
Connects to #613 
Demo using Joe Snuffy and other names  as the Veteran name but not TEST USER.
> Connects to #613 Fix Veteran Name in Demo

- Gemfile
- Gemfile.lock
> Upgrade nokogiri to 1.8.1 fix security warning

- app/controllers/api/v1/application_controller.rb
Adding Hearing Prep to the allowed roles
> Allow users with Hearing Prep to download docs via eFolder API

- Gemfile
- Gemfile.lock
Point to the latest `connect_vva` version that would retry SSL error 3 times
> Update connect vva to the latest version

- app/services/download_documents.rb
Quick tweak so we rescue properly.
Related to https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/537/
> move rescue

- Gemfile
- Gemfile.lock
- config.ru
Brings over Prometheus series collapsing from https://github.com/department-of-veterans-affairs/caseflow/pull/3726/files
Testing:
This changeset is identical to that in https://github.com/department-of-veterans-affairs/caseflow/pull/3726/files
> prometheus changes

- Gemfile
- Gemfile.lock
- README.md
- app/controllers/health_checks_controller.rb
- newrelic.yml
Connects https://github.com/department-of-veterans-affairs/caseflow/issues/3842.
As noted in https://github.com/department-of-veterans-affairs/caseflow/pull/3843, we have verified that we are not sending PII or env vars. I used the same HTTP header filtering here to ensure that we do not seen PII in headers.
> Add NewRelic

- app/jobs/download_manifest_job.rb
- spec/jobs/download_vva_manifest_job_spec.rb
Connects: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/690
> Only set manifest_vva_fetched_at when actually fetched

- db/migrate/20171115193142_add_index_download_id_document_id_to_documents.rb
- db/schema.rb
connects https://github.com/department-of-veterans-affairs/caseflow/issues/3921#issuecomment-344699028
> Add index [download_id, document_id] to documents

- Gemfile
- Gemfile.lock
This will might Sentry alert https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/578/
We will be catching an error if XML body is missing.
> Update connect VBMS to throw an error if body is missing in XML

- Gemfile
- Gemfile.lock
Fixes http://sentry.uat.ds.va.gov/sentry/efolder-uat/issues/559/
> Allow empty env var for VBMS client

- app/models/fetcher.rb
- app/services/prometheus_service.rb
Add prometheus monitoring to S3 requests
> Add S3 service metrics to prometheus monitoring

- Gemfile
- Gemfile.lock
Adds debugging statement in connect_vbms to track down this error: `undefined method at_xpath for nil:NilClass Did you mean? at_exit`
> Update connect vbms

- app/models/user.rb
- db/migrate/20171122181603_trim_user_email_addresses.rb
- db/schema.rb
- spec/models/user_spec.rb
> Trim whitespace from around user email addresses

- db/migrate/20171120161557_deduplicate_user_records.rb
- db/schema.rb
Connects #569. 
See [this comment](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/569#issuecomment-345375868) and the ones following it on the issue ticket for additional background.
> Add migration to deduplicate existing user data

- Jenkinsfile
copy paste from: https://github.com/department-of-veterans-affairs/caseflow/pull/4045
> Deployment announcements

- app/jobs/download_all_manifest_job.rb
- app/models/download.rb
- app/models/search.rb
- app/views/downloads/_confirm.html.erb
- spec/features/download_spec.rb
- spec/jobs/download_all_manifest_job_spec.rb
Connects #675.
I would like some in-progress feedback on this approach to solve the problem, while I finish up writing tests.
> Display error page when sidekiq dies and download status is 0

- Gemfile
- Gemfile.lock
must be coordinated with https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1087
this will start using path-matching for proxied requests
> Update VBMS and VVA

- app/controllers/api/v2/records_controller.rb
- app/models/manifest.rb
- app/models/record.rb
- app/services/manifest_fetcher.rb
- app/services/record_fetcher.rb
- config/routes.rb
- spec/models/record_spec.rb
connects #700 
TBD in the next PR:
* Automated tests
> Connect RecordsController to the v2 data model

- app/models/record.rb
- spec/requests/api/v2/records_spec.rb
- spec/services/record_fetcher_spec.rb
> More tests for the records controller

- db/migrate/20171211194628_deduplicate_user_records.rb
- db/schema.rb
Connects #740.
Final data migration stemming from #569.
> Remove duplicate user records and uppercase CSS IDs

- app/jobs/v2/download_manifest_job.rb
- app/models/manifest.rb
- app/models/manifest_source.rb
- spec/jobs/v2/download_manifest_job_spec.rb
- spec/models/manifest_source_spec.rb
- spec/models/manifest_spec.rb
- spec/requests/api/v2/manifests_spec.rb
> Fetch manifest async

- Gemfile
We need it to run in prod so we can use things like safety_assured.
> Moving zero downtime migration gem to production

- Gemfile
- Gemfile.lock
Updated gem version to include latest commit, features validations in particular.
> Nemo/Update commons gem version in Gemfile

- Procfile
- app/views/gui/_react.html.erb
- client/package.json
- config/application.rb
Connects #812.
From root efolder project directory you can now run `foreman start` to start the rails server, build the initial webpack file, fetch the latest webpacked js file on reload, and have webpack rebuild the js file whenever the source files change.
> Enable webpacker watching in local dev

- app/services/download_documents.rb
- spec/features/download_spec.rb
- spec/requests/api/v1/file_spec.rb
- spec/services/download_documents_spec.rb
This reverts commit df22a5d76cde91da0bbf8e4727119e4dc9c0559a.
> Revert "Removing documents from eFolder when no longer in VBMS (#883)"

- client/src/components/ManifestDocumentsTable.jsx
Connects #876.
Covering another edge case here. We want to display a message if we expect a list of documents and there are none.
> Display message for document list without documents

- client/src/containers/DownloadProgressContainer.jsx
> Make 'Try retrieving efolder again' button work

- client/src/containers/DownloadProgressContainer.jsx
Connects #898. Purely a cosmetic change here.
> Update button text and styling

- Gemfile
- Gemfile.lock
- spec/jobs/download_all_manifest_job_spec.rb
Connects #918.
Incorporates changes from [connect_vva PR#24](https://github.com/department-of-veterans-affairs/connect_vva/pull/24).
> Incorporate latest changes from connect_vva

- client/src/components/AlertBanner.jsx
Connects #928.
Tagging @Chingujo for visual design review, and tagging @mdbenjam for code review.
> Reduce spacing between banner title and description

- config/routes.rb
Will test this in UAT before it goes live to ensure that sidekiq is reachable.
> Move wildcard route behind sidekiq route

- client/src/apiActions.jsx
> Increase initial efolder UI manifest fetch timeout

- Procfile
Needed to run the shoryuken server to get queued jobs to run locally.
> Replace sidekiq process with shoryuken equivalent

- client/src/apiActions.jsx
https://github.com/department-of-veterans-affairs/appeals-support/issues/1762
https://github.com/department-of-veterans-affairs/appeals-support/issues/1761
When a user attempts to download multiple case files, we end up in a state where we have multiple case files polling at the same time. We then alternate updating the UI between the multiple case files. This code checks to see if this is the first call to polling, if it is, then we set the currentManifestId. If in a future poll we find that the currentManifestId is set to a new manifestId then we know a user has moved on to a new case file and we cancel this manifest's polling.
> Alternative solution

- Gemfile
- Gemfile.lock
Pull in changes from [BGS PR#53](https://github.com/department-of-veterans-affairs/ruby-bgs/pull/53).
> Update BGS gem

- Gemfile
- Gemfile.lock
See https://github.com/department-of-veterans-affairs/connect_vbms/pull/180
> Update connect-vbms reference

- Gemfile
- Gemfile.lock
Connects to https://github.com/department-of-veterans-affairs/connect_vbms/pull/184
> Update connect-vbms ref

- app/jobs/middleware/job_data_dog_metric_middleware.rb
- app/jobs/middleware/job_prometheus_metric_middleware.rb
- spec/jobs/job_prometheus_metric_middleware_spec.rb
> Rescue when sending metrics to Prometheus and DataDog

- app/controllers/api/v2/files_downloads_controller.rb
- app/controllers/api/v2/manifests_controller.rb
- app/models/files_download.rb
- app/models/manifest.rb
- app/models/serializers/v2/manifest_serializer.rb
Closes #6239
I refactored counting of documents to perform in Ruby instead of SQL. 
Before:
After:
> Optimize queries around record counts

- app/jobs/middleware/job_prometheus_metric_middleware.rb
- app/services/prometheus_service.rb
Connects: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1022
Action item from postmortem:
https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/docs/post-mortems/2018-06-12-prometheus-outage.md
> pushgateway metrics should be sent for all env

- Gemfile.lock
- app/services/external_api/vbms_service.rb
> Search for C file number when SSN has no files 

- app/models/manifest.rb
- db/migrate/20190307025848_remove_index_files_downloads_on_manifest_id_and_user_id.rb
- db/migrate/20190307034524_add_index_to_files_downloads.rb
- db/schema.rb
- spec/requests/api/v2/manifests_spec.rb
Connects to #1067 
This should fix race condition when using find_or_create. More context here: https://api.rubyonrails.org/classes/ActiveRecord/Relation.html#method-i-find_or_create_by
> Fix not unique error on find_or_create manifest and retry

- config/initializers/shoryuken.rb
Related to AWS RDS CPU utilization spikes
https://dsva.slack.com/archives/CHD7QU4L8/p1554320551035600
> Change retires times

- app/exceptions/bgs_error.rb
- app/exceptions/dependency_error.rb
- app/exceptions/vbms_error.rb
- app/services/external_api/vbms_service.rb
- config/environments/development.rb
- spec/exceptions/dependency_error_spec.rb
Filter for VBMS errors, similar (but different) what we have in Caseflow (see https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/exceptions/vbms_error.rb)
> Add VBMSError and parent DependencyError classes

- app/exceptions/vbms_error.rb
see https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/4812/events/315479/
> add VBMSError::FilenumberDoesNotExist

- db/migrate/20190508135156_add_fk_indices.rb
- db/schema.rb
All foreign keys should have an index on them.
> Add missing FK index

- app/services/manifest_fetcher.rb
> external service api changed to use file_number not source argument

- Jenkinsfile
Related to https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2142
> Add bake and build step to Jenkinsfile

- app/controllers/sessions_controller.rb
Trying to debug user unable to get proper redirect to Caseflow after successful PIV login.
> Additional logging on session authentication

- .rspec
- .simplecov
- app/controllers/application_controller.rb
- app/models/css_authentication_session.rb
- spec/features/backend_error_flows_spec.rb
- spec/spec_helper.rb
This PR does 2 things:
* adds more logging for SSO redirect logic
* captures the SAML first/last name attributes as separate fields
> SSO redirect logging, first/last name in session

- Gemfile
- Gemfile.lock
Adds new named exception classes.
> Update ruby-bgs gem

- app/controllers/health_checks_controller.rb
- config/environments/staging.rb
- config/environments/test.rb
- spec/requests/health_checks_spec.rb
We no longer have Prometheus Pushgateway so removing the env
> Remove ENABLE_PUSHGATEWAY_HEALTHCHECK env var

- README.md
> Clarify test requirements

- app/services/external_api/bgs_service.rb
If BGS CSS is down (as it is now in UAT) then we can temporarily work around it.
NOTE this will not work in production.
> Fake authz payload for use_ssoi_iam_fake_authz feature

- app/jobs/application_job.rb
- app/jobs/v2/download_manifest_job.rb
- app/jobs/v2/package_files_job.rb
- app/jobs/v2/save_files_in_s3_job.rb
Adds metadata similar to what we do in Caseflow. Also fixes the base class for these V2 jobs.
> Add relevant Raven metadata to jobs

- app/controllers/sessions_controller.rb
- spec/controllers/sessions_controller_spec.rb
> Redirect to / if already authenticated

- app/services/external_api/bgs_service.rb
As a UX convenience, we allow the station id to be null on the /login screen.
When it is, the authorization assumes the first station_id returned by the CSS service.
For that to work however, the initial CSS request must always use the system user so that the station_id field is not nil.
This fixes a small edge case most users will not encounter unless they leave the station_id field blank on /login.
> Allow station_id to be null, use system_user for initial CSS request

- client/.eslintrc.js
- client/package.json
- client/src/components/Icons.jsx
- client/src/containers/DownloadListContainer.jsx
- client/yarn.lock
- Updated ESLint to newest 
- Updated to latest `eslint-config-appeals`
- Adjusted ESLint settings accordingly
> Updates to ESLint

- app/models/manifest.rb
- app/services/document_counter.rb
If `skip_vva` feature toggle is set, will ignore VVAService.
> Add skip_vva feature toggle

- Gemfile
- Gemfile.lock
- spec/features/react_download_spec.rb
- spec/spec_helper.rb
> Retry flaky specs

- .circleci/config.yml
- docker-compose.yml
```
make down
docker volume rm caseflow-efolder_postgresdata
make up reset
```
> Upgrade postgres 11.7

- app/services/external_api/bgs_service.rb
- db/migrate/20200526154535_drop_v1_tables.rb
- db/schema.rb
Finish removing v1 references.
connects #1095 #1224
> Drop old tables, remove old feature toggle

- app/models/user.rb
- db/migrate/20200526161628_add_user_last_login.rb
- db/schema.rb
- spec/models/user_spec.rb
Step 1 of equivalent to https://github.com/department-of-veterans-affairs/caseflow/pull/10188
connects #1135 and #1228
> Add users.last_login_at, start treating CSS_ID as unique

- app/controllers/sessions_controller.rb
- spec/features/authentication_spec.rb
- spec/features/backend_error_flows_spec.rb
- spec/features/react_download_spec.rb
- spec/features/user_error_flows_spec.rb
- spec/models/user_spec.rb
- spec/requests/sso_spec.rb
Adds some test coverage for the SSO behavior, especially when serving Caseflow.
> Add sign in tests

- app/controllers/sessions_controller.rb
- spec/controllers/sessions_controller_spec.rb
Similar to #1245 
Handle non-HTML requests to /login endpoint
See https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/9500/events/4f0566e4bb0e44e0a53bf6170294f8bb/
> Handle JSON and text requests to /login endpoint

- Gemfile.lock
> Update newrelic gem

- app/services/exception_logger.rb
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/10667/events/9095b33c705b4843affb34ccb79a9da1/
> Fix UTF-8 encoding exception in error string matching

- db/migrate/20201201160251_change_record_id_to_bigint.rb
- db/schema.rb
Reverts department-of-veterans-affairs/caseflow-efolder#1265
> Revert "Bigint for record ids"

- Gemfile
- Gemfile.lock
1. Go to ...
BEFORE|AFTER
---|---
> eFolder: updated puma gem from 5.3.1 to 5.6.4

- Gemfile
- Gemfile.lock
- app/services/pdf_service.rb
- app/services/record_fetcher.rb
- spec/services/pdf_service_spec.rb
1. Go to ...
BEFORE|AFTER
---|---
> Mattray gov/appeals 8832 compression

- README.md
Resolves N/A
Update README formatting and with information about running at same time as Caseflow
1. Go to ...
BEFORE|AFTER
---|---
> Dev support/update readme

- Gemfile.lock
- Makefile.example
- README.md
- docker-compose-local.yml
- docker-compose-m1.yml
- Add `docker-compose-local.yml` and documentation about how to run Caseflow and Caseflow eFolder at same time.
- The `docker-compose-local.yml` file sets the postgresql ports to be same as what Caseflow uses and updates the redis image tag.
- Add M1/M2 make commands.
- 
1. Go to ...
BEFORE|AFTER
---|---
> Dev support/update setup

- config/initializers/omniauth.rb
Resolves https://jira.devops.va.gov/browse/APPEALS-26037
As a developer I need to update the ENV_SAML_ID value be an environment value so that the systems team can set the value specifically for ProdTest.
1. Go to ...
BEFORE|AFTER
---|---
> enable env_saml_id environment variable in omniauth config

- client/src/apiActions.jsx
- client/src/containers/DownloadContainer.jsx
- client/src/containers/WelcomeContainer.jsx
- client/src/reducer.js
Reverts department-of-veterans-affairs/caseflow-efolder#1414
> Revert "Anusha/appeals 20848 refactor"

- client/src/apiActions.jsx
- client/src/containers/DownloadContainer.jsx
- client/src/containers/WelcomeContainer.jsx
- client/src/reducer.js
Resolves https://jira.devops.va.gov/browse/APPEALS-19874
1. Go to ...
BEFORE|AFTER
---|---
> Revert "Revert "Anusha/appeals 20848 refactor""

- Gemfile
- Gemfile.lock
Reverts department-of-veterans-affairs/caseflow-efolder#1462
> Revert "hotfix/APPEALS-33769"

- config/initializers/omniauth.rb
1. Go to ...
BEFORE|AFTER
---|---
> Added logic for prodtest to use a specific ssoi

- config/initializers/omniauth.rb
1. Go to ...
BEFORE|AFTER
---|---
> Added logic for prodtest to use a specific ssoi (#1485)

- app/controllers/api/v2/records_controller.rb
- spec/requests/api/v2/records_spec.rb
The Caseflow-Reader app uses this API to show documents and will track if the document was sourced from AWS S3 or VBMS
1. Go to ...
BEFORE|AFTER
---|---
> add document source to records api v2 response headers

- docker-compose-local.yml
- docker-compose-m1.yml
- docker-compose.yml
Resolves [APPEALS-42246](https://jira.devops.va.gov/browse/APPEALS-42246)
1. Go to ...
BEFORE|AFTER
---|---
> Dev-Support/APPEALS-42246: Upgrade Redis to v6.2.6

- Gemfile.lock
Update with the latest commit ID of the CE-API gem
1. Go to ...
BEFORE|AFTER
---|---
> update gemfile with latest commit ID

- app/services/external_api/vbms_service.rb
- spec/services/external_api/vbms_service_spec.rb
Resolves [Migrate PagedDocuments](https://jira.devops.va.gov/browse/APPEALS-46214)
- Moves PagedDocuments service under new claim evidence API feature flag so that the CE API will take precedence over other APIs if enabled.
- Add specs to test functionality.
1. Run specs for changed file:
- `bundle exec rspec spec/services/external_api/vbms_service_spec.rb`
> Move PagedDocuments Under CE API Feature Toggle

- Gemfile
- Gemfile.lock
Resolves [Jira Issue Title](https://jira.devops.va.gov/browse/APPEALS-45599)
Update gemfile and gemfile.lock to point to the latest bgs gem ref version of Alex Smith's branch in the BGS repo.
**Branch:** https://github.com/department-of-veterans-affairs/ruby-bgs/commits/caseflow/add-new-security-endpoint/
**ref:** "0eec1272373ac15d0fb5547d8a46a86f692d3048"
**This newest version of BGS gem allows:**
Adds new endpoint for retrieving the sensitivity information for a non-veteran participant.
1. Go to ...
BEFORE|AFTER
---|---
> Update gemfile and gemfile.lock to point to new bgs version

- app/services/external_api/vbms_service.rb
- spec/services/external_api/vbms_service_spec.rb
1. Go to ...
BEFORE|AFTER
---|---
> Move PagedDocuments Under CE API Feature Toggle (#1573)

- Gemfile
- Gemfile.lock
Resolves [APPEALS-45599](https://jira.devops.va.gov/browse/APPEALS-45599)
Update gemfile and gemfile.lock to point to the latest bgs gem ref version of ruby-bgs master
Branch: https://github.com/department-of-veterans-affairs/ruby-bgs/commits/caseflow/add-new-security-endpoint/
ref: "a2e055b5a52bd1e2bb8c2b3b8d5820b1a404cd3d"
This newest version of BGS gem allows:
Adds new endpoint for retrieving the sensitivity information for a non-veteran participant.
1. Go to ...
BEFORE|AFTER
---|---
> Update ruby-bgs gemfile and gemfile.lock to new version

- Gemfile
- Gemfile.lock
Release for FY24Q3.3.0
1. Go to ...
BEFORE|AFTER
---|---
> Release/fy24 q3.3.0

- Gemfile.lock
- config/initializers/ruby_claim_evidence_api.rb
- Updates caseflow-efolder to use the latest version of the CE API gem.
> Add Logger to ruby_claim_evidence_api Initializer

- Gemfile.lock
1. Go to ...
BEFORE|AFTER
---|---
> Update gem file after bundle install

- app/controllers/api/v2/records_controller.rb
Resolves: APPEALS-46702
For API calls to eFolder and an S3 cache miss, eFolder would go back to VBMS and get document then store to S3 before returning to Reader. This store to S3 is unnecessary because an ActiveJob is kicked off in Reader when user browses the list of document and caches all the documents. Our update behind a feature flag will return the document and not try to save to S3 for API calls. The ActiveJob will take the existing path and store to S3.
Acceptance Criteria
Code compiles correctly
Testing Plan
https://jira.devops.va.gov/browse/APPEALS-49752
https://jira.devops.va.gov/browse/APPEALS-49753
BEFORE|AFTER
---|---
> add missing current user to feature flag

- app/controllers/api/v2/records_controller.rb
1. Go to ...
BEFORE|AFTER
---|---
> Change FeatureFlag to specify Users (#1630)

- app/controllers/api/v2/records_controller.rb
- app/models/record.rb
- app/services/record_api_fetcher.rb
- app/services/record_fetcher.rb
- app/services/record_fetcher_base.rb
- spec/requests/api/v2/records_spec.rb
Resolves APPEALS-46700
When Reader make an API call to eFolder to retrieve a document and document not found in the s3 cache, the eFolder will return the document directly from VBMS instead of first trying to store to s3. There is already another process that will store the document to s3
1. Go to ...
BEFORE|AFTER
---|---
> Feature/appeals 46700.4

- app/controllers/api/v2/application_controller.rb
- spec/controllers/api_v2_application_controller_spec.rb
Resolves [eFolder Express: Invalid search entry doesn't list max value for field][APPEALS-27846](https://jira.devops.va.gov/browse/APPEALS-27846)
Changes the error message in the function 'invalid_file_number()' begins on line 16 of application_controller.rb.
1. Go to ...
BEFORE|AFTER
---
|---
> Fixes error message on line 16 function: invalid_file_number

- app/controllers/api/v2/application_controller.rb
- spec/controllers/api_v2_application_controller_spec.rb
> Release R2.2.0 FY24Q4.2.0

- spec/models/manifest_spec.rb
Resolves [APPEALS-47113](https://jira.devops.va.gov/browse/APPEALS-47113)
Add Specs to Cover Additional Sensitivity Cases
> Add Specs to Cover Additional Sensitivity Cases

- README.md
resolves [APPEALS-55813](https://jira.devops.va.gov/browse/APPEALS-55812)
1. Go to ...
BEFORE|AFTER
---|---
> APPEALS-55813 Remove New Relic gem in eFolder Express

- app/controllers/api/v2/application_controller.rb
Resolves [eFolder>>View Result link on Recent Downloads throwing error page](https://jira.devops.va.gov/browse/APPEALS-57091).
- Use new method to check user/veteran sensitivity compatibility in the V2 ApplicationController.
- This will prevent the old "use BGS error to verify access" logic from running.
See Jira ticket.
> Use New Sensitivity Check Method

- spec/requests/api/v2/manifests_spec.rb
Resolves [eFolder>>View Result link on Recent Downloads throwing error page](https://jira.devops.va.gov/browse/APPEALS-57091).
Fix spec failures.
See Jira ticket.
> Update Specs to Address Failures

- client/src/apiActions.jsx
- client/src/containers/DownloadContainer.jsx
- client/src/containers/WelcomeContainer.jsx
Resolves [eFolder>>View Result link on Recent Downloads throwing error page](https://jira.devops.va.gov/browse/APPEALS-57091).
Send veteran file number in restart request to facilitate sensitivity check.
See Jira ticket.
> Send Veteran Number in Restart Request

- app/services/external_api/vbms_service.rb
- app/services/json_api_response_adapter.rb
Resolves (https://jira.devops.va.gov/browse/APPEALS-58177)
Added a check in the JsonApiResponseAdapter for an empty result.
1. Steps in https://jira.devops.va.gov/browse/APPEALS-58177
> add check for empty result

- config/initializers/deploy_env.rb
- lib/scripts/find_valid_veteran_file_numbers.rb
Resolves [Veteran IDs for UAT test scenarios](https://jira.devops.va.gov/browse/APPEALS-58216)
Adds script for finding valid UAT testing vets + their sensitivity levels.
1. Run the script via the Rails console:
```
s = FindValidVeteranFileNumbers.new
s.run
```
> Add Script for Finding Valid UAT Testing Users

- app/models/manifest.rb
Resolves 58216
Adjust UAT EXPIRY hours for testing
> Kev ma/appeals 58216 time adjust

- lib/scripts/find_valid_veteran_file_numbers.rb
Resolves [Veteran IDs for UAT test scenarios](https://jira.devops.va.gov/browse/APPEALS-58216)
Update error handling to catch all error types and log message.
1. Run the script via the Rails console:
```
s = FindValidVeteranFileNumbers.new
s.run
```
> Handle All Possible Errors in Script

- lib/scripts/find_valid_veteran_file_numbers.rb
Resolves [Veteran IDs for UAT test scenarios](https://jira.devops.va.gov/browse/APPEALS-58216)
- Sort output by sensitivity level.
- Display total result count for each level.
1. Run the script via the Rails console:
```
s = FindValidVeteranFileNumbers.new
s.run
```
> Improve Script Output

- app/controllers/api/v1/application_controller.rb
- app/controllers/api/v2/application_controller.rb
- app/controllers/api/v2/manifests_controller.rb
- app/jobs/v2/save_files_in_s3_job.rb
- app/models/manifest.rb
- app/services/external_api/vbms_service.rb
- client/src/apiActions.jsx
- config/initializers/deploy_env.rb
- spec/models/manifest_spec.rb
- spec/requests/api/v2/manifests_spec.rb
- spec/services/external_api/vbms_service_spec.rb
Resolves [59461](https://jira.devops.va.gov/browse/APPEALS-59461)
Combine send_current_user_cred_to_ce_api feature flag under use_ce_api flag. wrap all ce api related changes in one feature flag
- Run Rspec tests for changed files
- manifest_spec.rb
- manifests_spec.rb
- vbms_service_spec.rb
- application_controller_spec.rb
- api_v2_application_controller_spec.rb
Will need QA testing for document fetching and manifest retrieval functionality
> Kev ma/appeals 59461

- config/initializers/deploy_env.rb
> Kev ma/appeals 59461 update

- .rubocop.yml
- Gemfile
- Gemfile.lock
- Rakefile
> Release R2.6.0 FY24Q4.6.0

- .github/workflows/ecr-login.yml
- .github/workflows/requirements.txt
Update ECR token refresh job dependencies to work with the new `ubuntu-latest` image.
> dev-supporting/APPEALS-60527: Update ECR token refresh job dependencies

- app/controllers/api/v1/application_controller.rb
- app/services/error_handlers/claim_evidence_api_error_handler.rb
- app/services/external_api/vbms_service.rb
- app/services/sensitivity_checker.rb
- spec/requests/api/v2/manifests_spec.rb
- spec/services/error_handlers/claim_evidence_api_error_handler_spec.rb
- spec/services/external_api/vbms_service_spec.rb
- spec/services/sensitivity_checker_spec.rb
Resolves [Create/Improve eFolder Error Logging](https://jira.devops.va.gov/browse/APPEALS-61139)
- Updates eFolder to send improved logging data on Claim Evidence API error.
- Updates specs and supporting classes accordingly.
1. Run specs for changed files:
- `bundle exec rspec spec/services/external_api/vbms_service_spec.rb`
> Improve Claim Evidence API Error Logging

- .github/workflows/build.yml
GitHub workflow and Docker build PAT auth setup to connect internal repos
> APPEALS-57578 GitHub workflow PAT auth setup
