department-of-veterans-affairs/caseflow-efolder

config/initializers/session_store.rb
This means our cookies will expire 2 weeks from the last request (not
from the initial request)
=> Expire sessions after 2 weeks

config/initializers/logger.rb
Also redirects sidekiq log to application log
=> Use a different log_path for worker closes #68

app/helpers/application_helper.rb, app/views/layouts/application.html.erb, config/application.rb, config/environments/production.rb, spec/features/application_helper_spec.rb
* Configure account # via `Rails.configuration.analytics_account`
* Emit download events for `start` and `create` download 
* Due to redirects on `download#show`, pass analytics events via `ga_event` querystring parameter.
=> Add Google Analytics support

config/database.yml
Closes #107 
5 is most definitely too low for production and possibly too low for lower environments too.
=> Make database connection pool size configurable

app/assets/stylesheets/_main.scss, app/assets/stylesheets/_tabs.scss, app/views/stats/show.html.erb
Positioning as an extension to USWDS, given @KHarshawat's view of the general applicability of this. Maybe that's not appropriate? Also note that the class has been named `usa-table-no-header` as an indication of when it is appropriate to use.
=> CSS changes requested by Kavi

app/models/download.rb
closes #213 ...I hope. If not, there's no reliable way to reproduce the order of documents in VBMS.
=> Secondary sort by id for docs with same date

app/services/download_documents.rb, spec/services/download_documents_spec.rb
And filter out the XML versions of `999981 - C&P Exam` docs that are also sent as PDFs.
Closes #211
=> Add support for filtering vbms doctypes

app/models/download.rb
fixes #213, apparently we're displaying docs with same receipt date backwards from VBMS.
=> Match VBMS ordering of documents

app/jobs/demo_get_download_manifest_job.rb, app/jobs/get_download_manifest_job.rb, app/models/download.rb, app/models/search.rb, app/views/downloads/_confirm.html.erb, spec/features/download_spec.rb, spec/jobs/get_download_manifest_job_spec.rb, spec/models/search_spec.rb
This PR:
- Adds support for "DEMO_VBMS_ERROR" and "DEMO_NO_DOCUMENTS" file_number for triggering desired error
- Logging VBMS connection errors and sending them to sentry 
- Updated error messaging on VBMS connection error during search
New UI:
Testing:
- Running `rake`, all current tests pass
- New unit and feature tests have been added and pass
- VBMS error properly displays in Sentry:
- VBMS error properly shows up in logs:
=> Handle VBMS connection errors

README.md
One more README tweak, didn't realize i added partially duplicated info.
=> moves redis instructions further up in the README

app/models/download.rb, app/services/bgs_service.rb, config/database.yml, db/migrate/20161011020910_add_first_name_last_name_ssn_to_downloads.rb, db/schema.rb, lib/fakes/bgs_service.rb, spec/features/download_spec.rb, spec/models/download_spec.rb, spec/models/search_spec.rb, spec/services/bgs_service_spec.rb, spec/services/download_documents_spec.rb
Changes download filename to "LastName, Firstname - Last4SSN". This was significantly more difficult than first anticipated! Adds a DB migration to store the last four digits of a veteran's ssn, and the first and last name in separate columns. A bit of tech debt is also cleaned up here and there for good measure.
Fixes #223
Fixes #55 
Reviewer: @shanear 
Test plan:
modified and added unit tests
locally tested that the file download now occurs with the expected format
tested the migration and rollback several times
TODO: currently blocked on testing this with the live DB. @shanear, can you help me figure out how to proceed?
=> Updates .zip filename to match format  "LastName, Firstname - Last4SSN"

.ruby-gemset
Sounds like everyone is using rbenv, which is cool. I just happened to already have RVM installed on my machine so would prefer to add a .ruby-gemset file. Shouldn't affect anyone else, I believe. Does this seem reasonable? Otherwise I can just keep it uncommitted locally.
=> Add ruby-gemset to repo

app/views/downloads/_progress.html.erb, spec/features/download_spec.rb
If any of the files have failed to download, the user can retry by
clicking a CTA button. Updating the text from "Retry Download" to "Try
Retrieving eFolder Again"
Testing:
- Tests all pass
- Manual searched for "DEMO3", error message & CTA button rendered as expected:
CC @lakohl took some small liberty in capitalizing all the words in the button to match the "Download Anyway", let me know if this was incorrect!
=> Update cta button text for retrying download

app/controllers/downloads_controller.rb, app/services/download_documents.rb, spec/features/download_spec.rb
Testing:
- All tests pass
- Added tests that specifically test a non-existing download 
- Manually testing in the browser works as expected:
=> Return 404 on non-existing download attempt

app/assets/stylesheets/_download.scss, app/jobs/demo_get_download_manifest_job.rb, app/views/downloads/_progress.html.erb, spec/features/download_spec.rb
=> Show document ID for errored downloads

app/assets/stylesheets/_download.scss, app/views/downloads/new.html.erb
- Add note to download history explaining how long downloads persist
Fixes #261 
Testing:
Manually loaded in browser, now looks like
=> Add note to download history

Jenkinsfile
By allowing APP_ENV to be overridden through environment variables, Jenkins can inject custom properties in the pipeline. This way, we can use the same Jenkinsfile for different AWS environment.
=> Allow APP_ENV to be overridden through ENV

app/assets/javascripts/application/download_status.js, app/views/downloads/_confirm.html.erb, spec/features/download_spec.rb
Fixes #33 
Testing:
- Added feature tests to verify it does and does not call  `window.DownloadStatus.init()` as expected
- All current tests pass
- Manual browser testing, everything worked as expected
=> Only poll for download status when fetching manifest

app/views/downloads/_progress.html.erb
Added: "(Remember that Virtual VA documents are not included in this download)" on the download eFolder page.
Fixes #267 
**Test Plan**
-Ran test suite locally.
-Verify the new text is correct: ![screen shot 2016-10-24 at 4 44 20 pm](https://cloud.githubusercontent.com/assets/3885236/19663251/32f0c478-9a09-11e6-8f97-63eb4359b324.png)
=> Updated the text on the download eFolder page.

app/models/download.rb, app/views/downloads/_progress.html.erb
Update the download progress bar to show the number of files remaining, and move the notice that you can close that page at any time above the progress bar.
Fixes #259 
**Test Plan**
- Run test suite
- Verify the new text is there
=> Clarify Files Complete Progress

Jenkinsfile
1. The `dir` command was wrong, the correct home for ansible playbooks is now `/ansible` so for Jenkins it's `appeals-deployment/ansible`
1. There's actually no need to change directory, the git submodule commands can be run from the root.
=> Git submodule commands should run from root dir

app/assets/stylesheets/_main.scss, app/models/download.rb, app/views/downloads/new.html.erb
Removed the text saying that downloads are deleted in 72 hours and added specific delete dates to each download.
Fixes https://github.com/department-of-veterans-affairs/appeals-pm/issues/781
**Test Plan**
-Run the test suite
-Check the text on the page:
=> Added the date a downloaded eFolder will be deleted.

app/controllers/application_controller.rb
Otherwise causes 
```
NoMethodError (undefined method `id' for nil:NilClass):
app/controllers/application_controller.rb:22:in `set_raven_user'
```
See https://github.com/department-of-veterans-affairs/caseflow-certification/blob/master/app/controllers/application_controller.rb#L39-L47 for similar implementation of this functionality.
=> only log sentry user if there's a current_user

Gemfile
Allow gem source to be overridden by `GEM_SERVER_URL`. This URL will port to an internal gem server in deployment scripts.
See also https://github.com/department-of-veterans-affairs/appeals-deployment/pull/198
=> Allow Gem source to be overridden by env

app/controllers/application_controller.rb, app/views/layouts/application.html.erb, config/environments/development.rb, config/environments/test.rb, spec/features/send_feedback_spec.rb
Links point to Caseflow Feedback in the dropdown and on bottom right if an env variable is set.
To enable this in prod and uat, we'll need to set `ENV["CASEFLOW_FEEDBACK_URL"]`
Testing:
Link works locally, points to demo.
=> Adds link to Caseflow Feedback

app/models/search.rb, db/migrate/20161220180421_add_css_id_to_downloads_and_searches.rb, db/schema.rb, spec/features/download_spec.rb, spec/models/search_spec.rb, spec/rails_helper.rb
1. Rename `user_id` to `css_id` in `searches` and `downloads`
2. Add `users` table, add `user_id` to `searches` and `downloads`
3. Fix code to use `css_id` instead of `user_id`
Next steps:
1. Remove columns: css_id, email, user_station_id from `searches` and `downloads`
2. Re-factor code to access user data through the `users` table 
connects #325
=> Add 'users' table, rename user_id to css_id in downloads and searches

db/migrate/20161221143629_remove_user_id_from_searches_and_downloads.rb, db/schema.rb
Connected to #325. This is PR 3 that just removes `user_id` from the `searches` and `downloads` tables. Details are in #325. 
Testing:
* Migration ran without errors
=> Remove user_id from searches and downloads

app/models/download.rb, db/migrate/20170103161212_remove_css_id_station_id_from_downloads_searches.rb, db/schema.rb, spec/features/dashboard_spec.rb
This is the last PR to remove `css_id`, `user_station_id` and `email` from downloads and searches. 
Note: I have been debating whether I should be raising `ActiveRecord::IrreversibleMigration` in `down` method because the actual data is not reversible. 
connects #325
=> Remove css_id, user_station_id, email from searches and downloads

app/controllers/downloads_controller.rb, app/models/download.rb, app/services/download_documents.rb, db/migrate/20170106143608_add_zipfile_size_to_downloads.rb, db/schema.rb, spec/features/download_spec.rb, spec/services/download_documents_spec.rb
Also, store the filesize to the database as a way of caching it because `File.size` can
take several seconds on files of ~1GB. Additionally allows us to query
the size of downloads.
connects #299
Before:
After:
=> Add Content-Length header to zip download

app/controllers/downloads_controller.rb, app/jobs/demo_get_download_manifest_job.rb, app/models/download.rb, app/views/downloads/_progress.html.erb, spec/features/download_spec.rb, spec/models/download_spec.rb
For a progress bar "X of XXX files remaining", use `download_status` to count in-progress documents instead of `completed_at` timestamp. Using `completed_at` would work on the first attempt to download the documents but it would not work on the second attempt because documents with `success` status were marked as completed on the first attempt. 
connects #353
=> Progress bar: fix the progress on the second and later download attempts

Gemfile.lock
This was causing build breakage due to security vulnerability issue.
=> Nemo/Changed rubyzip version to 1.2.1

app/assets/javascripts/application/download_progress.js, app/assets/javascripts/application/download_status.js
Polls less aggressively on the client side so slow connections to the VA network don't cause occasional browser hangs.
This issue was reported due to the `setInterval` in  `download_status.js`, but I fixed it in `download_progress.js` too for good measure.
Fixes #373.
Test plan:
Added a sleep to `downloads_controller#show`, and a bunch of console.logs. Verified that no more than the permitted # of requests are fired off at a time. 
```
def show
@download = downloads.find(params[:id])
sleep 3
respond_to do |format|
format.html
format.json { render json: @download.to_json }
end
end
```
=> Poll less aggressively

Gemfile, Gemfile.lock, app/models/document.rb, app/services/download_documents.rb, app/services/vbms_service.rb, db/migrate/20170314163630_add_type_description_to_documents.rb, db/schema.rb, spec/jobs/get_download_manifest_job_spec.rb, spec/models/document_spec.rb, spec/services/download_documents_spec.rb
1. Connect to VBMS eFolder service v1 if `USE_VBMS_V5` is enabled
2. Add `type_description` column to `documents`
3. Make the code work for both versions. 
4. Create subsequent tickets that will be implemented when we switch to a new service completely.
[#416](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/416)
[#415](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/415)
connects #418
=> Use VBMS eFolder service v1

app/assets/stylesheets/_main.scss
Removes the magnifying that was underneath the eFolder "Search" button.
Connects https://github.com/department-of-veterans-affairs/caseflow/issues/1606
=> Remove magnifying glass icon on "Search" button

Jenkinsfile
This minor change force the deployment pipeline to use Jenkins deploy node. This is needed because the Deploy node is in Utility VPC, and has connectivity to UAT and Prod VPC.
=> Use Jenkins deploy node for deployment

app/assets/stylesheets/_download.scss, app/jobs/demo_get_download_files_job.rb, app/jobs/demo_get_download_manifest_job.rb, app/views/downloads/_confirm.html.erb, app/views/downloads/_progress.html.erb, app/views/downloads/new.html.erb, spec/features/download_spec.rb
This is an FE piece for VVA. VVA is hidden behind the Feature Flag `vva_service` in UAT and Prod. Per agreement with Lara, `source` column will not be hidden behind the feature flag so it will be visible once this is merged. 
connects #488 
Example when the VVA flag is enabled:
=> Implement FE changes for VVA

config/environments/production.rb
config was spelled conig in production.rb.
=> Fixing typo

app/views/layouts/application.html.erb, config/application.rb, config/environments/production.rb
Connect #548.
To test, log into GA and see metrics showing up. For instance:
Our past implementation tried to avoid sending data when running not in production. I suspect that additional complexity is why we accidentally were not sending data for anything, including production. It's dangerous when developers cannot verify the correct behavior locally.
Instead, we log all data. In the GA interface, we can use filtering tools to limit queries to only be the prod domain.
=> Re-enable GA

config/application.rb, config/environments/development.rb
- Connects #556 
- Connects https://github.com/department-of-veterans-affairs/caseflow/issues/2340
- Exposes `Accept-Ranges` so PDF.js can read the value
- Limits access through CORS
To test:
- Run Caseflow on port 3000, and eFolder on port 4000. Enable the feature flag and make sure we get the documents from eFolder.
- Enable the feature flag by executing `FeatureToggle.enable!(:efolder_docs_api)` in the rails console for Caseflow
- Load the document list (http://localhost:3000/reader/appeal/reader_id1/documents) and click on any document in the list
- Ensure all requests to efolder complete with a HTTP status of 200 and there are no errors stating `Refused to get unsafe header "Accept-Ranges"`
=> Exposing HTTP header for Reader

app/controllers/api/v1/application_controller.rb, app/controllers/api/v1/files_controller.rb, spec/requests/api/v1/file_spec.rb
Connects: #535
We currently don't handle error cases properly. If a user doesn't pass the correct headers, we get a sentry error. This change updates the API to return 400's if any headers are missing.
=> API Error Cases

app/controllers/api/v1/files_controller.rb, app/models/serializers/v1/download_serializer.rb, spec/requests/api/v1/file_spec.rb
Connects: #2873
For some reason this bug seems to manifest itself on UAT but not locally. It seems on UAT rails correctly converts user -> user.id when it tries to find the record. But if that record is not found it appears to convert user -> nil when creating the record. I cannot seem to reproduce this locally, but it is tested on UAT and appears to fix the problem.
=> User.id bug

app/assets/stylesheets/_main.scss
Connects #564 
Ensure that there is not an extra line below the last document in the doc manifest (e.g. below 'Birth Certificate' in the mock) on the the Retrieve eFolder page or on the Download eFolder page.
=> Extra lines below last document in doc manifest

app/jobs/middleware/job_prometheus_metric_middleware.rb, app/middleware/metrics_collector.rb, app/services/external_api/bgs_service.rb, app/services/external_api/vbms_service.rb, app/services/external_api/vva_service.rb, app/services/metrics_service.rb, app/services/prometheus_service.rb, config.ru, config/initializers/sidekiq.rb, config/secrets.yml, spec/jobs/job_prometheus_metric_middleware_spec.rb, spec/services/metrics_service_spec.rb, spec/services/prometheus_service_spec.rb
connects https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/362
connects #438
Mainly copied Metrics services from Caseflow
- Refactored some service calls to add MetricsService aka Prometheus
- BGS/VBMS/VVA should all be pushed to prometheus
To test:
- Spin up using `RAILS_ENV=prod`
- Test any of the external API calls
- Watch prometheus yell at you that it can't push to your non-existent gateway.
```
background_jobs_summary{type="failed",quantile="0.5"} 228
background_jobs_summary{type="failed",quantile="0.9"} 228
background_jobs_summary{type="failed",quantile="0.99"} 228
background_jobs_summary_sum{type="failed"} 8436
background_jobs_summary_count{type="failed"} 37
background_jobs_summary{type="default_queue_latency",quantile="0.5"} 0 …
```
=> Adding Prometheus

app/assets/stylesheets/_main.scss, app/views/downloads/_confirm.html.erb, app/views/downloads/_progress.html.erb, app/views/help/_faqs.html.erb, app/views/help/_faqs_with_vva.html.erb
Connects #574 
1. As a user I would like to be able to see the column labels when I scroll through the list of files eX is retrieving. Currently the table headings scroll with the doc list.
=> Table header scrolls with the doc manifest

app/models/download.rb, app/models/search.rb, db/migrate/20170809174911_add_from_api_to_downloads.rb, db/schema.rb, spec/models/download_spec.rb, spec/models/search_spec.rb, spec/requests/api/v1/file_spec.rb
Connects: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/586
In order to separate the effects of the new eFolder API from the UI we're adding a flag to the Download table that will mark downloads as coming from the api or not. The API should only update documents that were created via the API and the UI should only update documents that were created via the UI.
**Test Plan**
=> Add new from_api flag to DB

app/assets/javascripts/application/download_progress.js, app/views/downloads/_progress.html.erb
Table header scrolls with the doc manifest (#574)
Removed the class that was hovering the header and replaced it with a class that leaves header fixed.
=> Table header scrolls with the doc manifest (#574)

app/assets/stylesheets/_download.scss
Connects #622 
AC
1. Verify that all table headers: Document Type, Source, and Receipt Date display as left aligned in all browsers.
**IE**
**FireFox**
=> Connects to Left Align table headers in IE (#622)

Gemfile, Gemfile.lock
This points to the latest version of connect VVA. 
Description of the problem here:
https://github.com/department-of-veterans-affairs/connect_vva/issues/13
=> Update connect vva to reject DH key exchange

app/models/search.rb
Connects: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/647
When you search for an eFolder via the UI we create a search object. If the download is new, we create a new download record to associate with the search object. We then do a validation on that download object to see if 1) the veteran exists, 2) the user has access to this case file's sensitivity. If either of these fail, the intention is for the download object not to be saved to the DB.
However, since we set the search object's download attribute to `self.download = Download.new()` if we ever save anything from this search record to the DB, we'll inadvertently save this download object as well #railsmagic. In the validate method if either of the failure cases exist: 1) the veteran exists, 2) the user …
=> Fixing hanging download bug

app/assets/stylesheets/_download.scss
Connects #686 
AC:
1. Source and Receipt Date should be present for each failed documents.
2. Ensure Source and Receipt Date are inside the tab.
=> Connects to Errors tab - source and receipt date are off (#686)

app/models/fetcher.rb
Connects: https://github.com/department-of-veterans-affairs/caseflow/issues/3782
This is hard to reproduce locally since my staging env is not hooked up to S3, but am using the fake S3 service. But I'm pretty convinced this will fix the current issues with eFolder.
The behavior we're seeing in UAT is that cases fail the first time their downloaded and succeed the second time if you clear the cache. When looking at the downloaded pdf files in the zip file from the first download, we see that the file contents are `#<Aws::S3::Object:0x007fce682bfac8>`. Looking at the code, we expect `S3.store_file` to return the file. While the fake version does, the real version does not. We add an explicit return to fix this.
It works on a subsequent download because the right value was cached in S3, and …
=> Real S3 service doesn't return the file when you call store

app/jobs/restart_stalled_downloads_job.rb, app/models/download.rb, app/models/search.rb, lib/fakes/bgs_service.rb, lib/fakes/document_service.rb, spec/models/download_spec.rb
Connects #662.
Allows access to demo cases with arbitrary numbers in veteran ID following "DEMO". This behaviour appears to have been inadvertently disabled as part of a larger change (https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/634/files#diff-7f299968f69db6bfed17c513dd12bd34). I chatted with the Sunil and he seems to recall removing it to test the case where an incorrect veteran ID triggers the appropriate alert. We can still trigger that alert so I don't think this change is a regression.
Also, makes the pattern for demo veteran IDs more strict (allows only ^DEMO.* now, previously was .*DEMO.*), and makes demo? functions return boolean values.
=> Allow arbitrary DEMO### veteran IDs

app/jobs/download_files_job.rb, config/initializers/sentry.rb
Connect #669.
I used a Sentry processor to trigger a breakpoint when Sentry was going to log an exception. I applied the following diff:
```diff
diff --git a/app/jobs/fakes/download_files_job.rb b/app/jobs/fakes/download_files_job.rb
index 5f51068..2d5fc5f 100644
--- a/app/jobs/fakes/download_files_job.rb
+++ b/app/jobs/fakes/download_files_job.rb
@@ -2,6 +2,8 @@ class Fakes::DownloadFilesJob < ActiveJob::Base
queue_as :default
def perform(download)
+    puts "~~~~~ ++++++== ================ raising error fak ============================="
+    raise 'fak'
demo = Fakes::DocumentService::DEMOS[download.file_number] || Fakes::DocumentService::DEMOS["DEMODEFAULT"]
Fakes::DocumentService.errors = demo[:error]
diff --git a/config/initializers/sentry.rb b/config/initializers/sentry.rb
index …
```
=> Do not log EOFError to Sentry

app/jobs/download_files_job.rb
`DownloadFilesJob` might make BGS calls if veteran info is nil on the download object. BGS service requires current user information.
This should fix Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/601/
connects #704 
Steps to Reproduce
1. Find a download that has nil for either ssn, first_name or last_name
2. Search for a manifest, check that one of those fields are nil in the download record
3. Start retrieving files, observe if Sentry receives the alert https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/601/
=> Set the current user in the request store

app/models/download.rb, app/views/downloads/_progress.html.erb
Connects #587 
When retrieving files from eFolder,
estimated time disappears here and there for some strange reason.
=> Retrieving Files | Estimated time disappears 

app/models/manifest.rb, app/models/manifest_source.rb, app/models/record.rb, db/migrate/20171122161202_rename_manifest_statuses_to_manifest_sources.rb, db/migrate/20171122161559_rename_manifest_id_to_manifest_source_id_in_records.rb, db/schema.rb, docs/v2/database_structure.md
Update to the v2 data model. We need to connect `records` to `manifest_sources` so we know where the document came from.
Reference: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/docs/v2/database_structure.md
=> Records need to be associated with the manifest source table

Gemfile, Gemfile.lock
Updated caseflow-commons dependency to [newest version](https://github.com/department-of-veterans-affairs/caseflow-commons/commit/a8d42e6563277144938f0a513ee601233814ff86) from previous oldest version. The [only changes](https://github.com/department-of-veterans-affairs/caseflow-commons/pull/120) to caseflow-commons included in this upgrade are CSS changes to the remove a deprecated dark red color in favor of the lighter red we've settled on in [the style guide](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide).
=> Update Gemfile to use newest caseflow-commons version

app/models/user.rb, spec/models/user_spec.rb
Connects #717.
Caseflow was previously not saving the CSS ID to the "user" element of the session. [This PR for caseflow](https://github.com/department-of-veterans-affairs/caseflow/pull/4128) added the CSS ID to the default fake user (as well as the efolder role), so that should address the root of the problem.
The code changes in this PR allow for a more graceful handling of this state should it arise again.
=> Do not attempt to create User db row unless we have CSS_ID and station_id

app/jobs/restart_stalled_downloads_job.rb, lib/fakes/bgs_service.rb
This probably should have been cleaned up as part of #710, but I missed it then and just noticed it now so I'm doing it now.
=> Unify logic to check if file is a demo

app/models/document.rb, app/services/download_documents.rb, spec/models/document_spec.rb, spec/services/download_documents_spec.rb
Connects #736.
I think this happened because somebody clicked "Try retrieving efolder again" while another job was waiting to be completed. This called `DownloadsController.retry()` which called `Download.reset!()` which sets `Document.filepath` to nil. I can confirm this with more investigation into the logs if we need.
This fix simply sets the document's filepath if it is nil so we have somewhere to download the document to.
=> Set document filepath before downloading document from S3

app/services/image_converter_service.rb, spec/models/document_spec.rb, spec/models/fetcher_spec.rb, spec/models/record_spec.rb, spec/services/image_converter_service_spec.rb
We only convert an image if `converted_mime_type` returns a new mime_type. This adds a feature toggle to force `converted_mime_type` to return the original mime_type and therefore not convert the image.
=> Adding feature toggle to disable conversion of tiff's to pdfs

Gemfile, Gemfile.lock, app/services/data_dog_service.rb, app/services/metrics_service.rb
This PR matches https://github.com/department-of-veterans-affairs/caseflow/pull/4160.
I tested this with the following in the console:
```
MetricsService.record("test description", service: :image_magick, name: "image_magick_convert_tiff_to_pdf") do puts "fake" end
```
and then checked to see that metric show in up DataDog.
=> Update metrics service to send to DataDog

app/jobs/download_manifest_job.rb, app/services/exception_logger.rb, app/services/manifest_fetcher.rb, config/initializers/sentry.rb, spec/services/exception_logger_spec.rb
connects #763 
When VVA/VBMS is down, connect_vva and connect_vbms correctly catch the exception that is then passed to the eX and download gets a status of vva_connection_error or vbms_connection_error. 
When VBMS or VVA is in maintenance, do not capture these errors in Sentry.
Unfortunately, Sentry `excluded_exceptions` doesn't provide support for regular expressions so I created our own  class to exclude certain exceptions. 
See here what Raven does: https://github.com/getsentry/raven-ruby/blob/00c572b281b0862e2fbb7872b28c95e7c2578949/lib/raven/configuration.rb#L331
=> Sentry - Ignore exceptions when VBMS/VVA are in maintenance

Gemfile, Gemfile.lock, app/services/data_dog_service.rb, app/services/metrics_service.rb
I used the same testing process as https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/776. I installed the macOS DataDog agent so this new approach could work.
In the screenshot below, you can see the data showing up ([sample notebook](https://app.datadoghq.com/notebook/23056/Delete%20this%20after%20caseflow-efolder%23789%20is%20merged)):
Here is the data from UAT:
=> Switch DataDog to use dogstatsd

lib/fakes/bgs_service.rb, spec/features/download_spec.rb, spec/jobs/job_prometheus_metric_middleware_spec.rb, spec/jobs/save_files_in_s3_spec.rb, spec/models/download_spec.rb, spec/models/manifest_spec.rb, spec/models/search_spec.rb, spec/models/veteran_spec.rb, spec/rails_helper.rb, spec/requests/api/v1/file_spec.rb, spec/requests/api/v2/manifests_spec.rb, spec/services/image_converter_service_spec.rb, spec/services/record_fetcher_spec.rb
The [pull request to run efolder tests in a random order](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/761) has been revealing a lot of tests that should fail but pass due to the order in which they are run. I had initially planned to fix all of those cases (thinking there would be few) in the same PR that randomizes the test order in Travis, however due to the large number of falsely passing tests, I think it best to incorporate in distinct PRs so they can be merged to master as soon as possible. This is the first batch of those test fixes.
=> Lowell test fixes 1

spec/rails_helper.rb
Improvement upon the [initial version](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/794/commits/cd9f31b4d4cbc917c2fdca2e4597990d3ddabae3?diff=unified#diff-e11bdaf9116be3911e9557b69e242370R82) using `SecureRandom.uuid()` instead of the homespun version I hacked together (h/t Alan).
=> Replace homespun document ID generator with SecureRandom version

app/models/download.rb, spec/models/download_spec.rb
Connects #778.
This piece will need to be deployed before [the other PR](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/797) associated with #778 in order to avoid issues where the code executes expecting the `filepath` column and it is not there.
=> Remove references to Document.filepath from app logic

Gemfile, Gemfile.lock, app/controllers/api/v1/application_controller.rb, app/jobs/v2/download_manifest_job.rb, app/models/record.rb, app/services/document_creator.rb
Since we can't turn on VBMS eFolder V1 yet, we need to continue using the old eDocument service for the v2 api. 
Tested using VBMS and VVA file numbers pointed to UAT env.
=> V2 api - use VBMS ListDocuments

app/models/manifest_source.rb, app/models/serializers/v2/manifest_serializer.rb, app/services/manifest_fetcher.rb
1. Set manifest status to pending before starting asynchronous job
2. Catch StandardError while fetching manifest to change the status from pending to failed.
=> Set manifest pending status synchronously

app/controllers/api/v1/documents_controller.rb, app/controllers/api/v2/records_controller.rb
Connects: #814 
Currently eFolder caches error responses. This can cause Reader users to get error versions of our pages because they retrieved a document during an outage, and cached the response.
**Test Plan**
=> Stop caching when sending errors

config/application.rb
The new eFolder API (v2) needs CORS enabled to service requests from other domains. We've already enabled v1, so we updated the allowed URLs to include v2.
**Test Plan**
=> Enable CORS for v2

Gemfile, Gemfile.lock, README.md, app/models/document.rb, app/models/fetcher.rb, app/models/record.rb, app/services/download_documents.rb, app/services/image_converter_service.rb, app/services/metrics_service.rb, app/services/record_fetcher.rb, db/migrate/20180106211625_add_conversion_status_to_records.rb, db/migrate/20180108170052_add_conversion_status_to_documents.rb, db/schema.rb, lib/fakes/document_service.rb, spec/models/document_spec.rb, spec/models/fetcher_spec.rb, spec/models/record_spec.rb, spec/rails_helper.rb, spec/services/image_converter_service_spec.rb, spec/services/record_fetcher_spec.rb, spec/utility_functions.rb
This PR does two things:
1) Removes code calling Image Magick directly and instead calls our new image conversion service.
2) Changes both the v1 and v2 APIs to fail gracefully if conversion fails. If it fails we now return the original file (i.e. TIFF image) instead of failing.
**Test Plan**
- Ensure the `:convert_tiff_images` feature flag is turned on.
- Testing locally by commenting out this line: https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/mdbenjam-call-convert-service/lib/fakes/document_service.rb#L88 so that we only return TIFFs then going through the UI, new and old document APIs to ensure the following:
- If the conversion service is running (see new readme instructions), then the images are converted from TIFF to PDF
- If the conversion service is not …
=> Call new Image Magick Service

app/services/image_converter_service.rb
Looks like there's a second exception that can be raised from our service. Catching it here to handle gracefully.
**Test Plan**
=> Catching timeout exceptions

app/models/manifest.rb, app/models/manifest_source.rb, app/models/serializers/v2/manifest_serializer.rb, db/migrate/20180123192853_rename_source_to_name_in_sources.rb, db/schema.rb, lib/fakes/document_service.rb, spec/jobs/v2/download_manifest_job_spec.rb, spec/jobs/v2/package_files_job_spec.rb, spec/jobs/v2/save_files_in_s3_job_spec.rb, spec/models/manifest_source_spec.rb, spec/models/manifest_spec.rb, spec/models/record_spec.rb, spec/requests/api/v2/files_downloads_spec.rb, spec/requests/api/v2/records_spec.rb, spec/services/document_creator_spec.rb, spec/services/image_converter_service_spec.rb, spec/services/manifest_fetcher_spec.rb, spec/services/record_fetcher_spec.rb
Rename `manifest_source.source` to `manifest_source.name` as it is a better name for the column.
=> Rename manifest source - source column

Gemfile, Gemfile.lock, app/helpers/application_helper.rb, app/jobs/v2/download_manifest_job.rb, app/jobs/v2/package_files_job.rb, app/models/manifest.rb, app/models/manifest_source.rb, app/models/record.rb, app/services/record_fetcher.rb, app/services/zipfile_creator.rb, lib/fakes/document_service.rb, spec/jobs/v2/download_manifest_job_spec.rb, spec/services/record_fetcher_spec.rb, spec/services/zipfile_creator_spec.rb
1. Handle edge case: when two users might start the same job for the same manifest/source at the same time. 
2. Add additional logic if a current user doesn't have eX role, start saving files in s3 job
=> Mutex manifest download job and package files job

app/services/document_creator.rb, spec/services/document_creator_spec.rb
Delete records if there were perviously created in Caseflow DB but no longer exist in VBMS.
=> Remove unneeded documents

config/routes.rb
Resolves the two following deprecation warnings when starting the rails server:
```
DEPRECATION WARNING: Defining a route where `to` is a symbol is deprecated. Please change `to: :start` to `action: :start`. (called from block (4 levels) in <top (required)> at /Users/lowell/Projects/efolder/config/routes.rb:37)
DEPRECATION WARNING: Defining a route where `to` is a symbol is deprecated. Please change `to: :progress` to `action: :progress`. (called from block (4 levels) in <top (required)> at /Users/lowell/Projects/efolder/config/routes.rb:38)
```
=> Fix deprecation warning

app/controllers/gui_controller.rb, app/views/gui/_react.html.erb, client/package.json, client/src/containers/HelpContainer.jsx, client/src/containers/InitContainer.jsx, client/src/index.jsx, client/webpack.config.js, client/yarn.lock, config/routes.rb
In the course of working on #805 I realized we would need to convert the help page to react and we had overlooked making tickets for this work. This PR encompasses the work to make the help page work in the new react single page app.
Ideally we wouldn't need to get the path to the different assets from the store and could instead get them from some other API response, but I think this is good enough for now. If we are able to remove the other properties we are passing in through `initial_react_data` in the work that happens in #804, #806, and #808 then we should investigate alternative approaches to getting the paths to those assets.
=> Move help page into react

Gemfile, Gemfile.lock
Upgrade `omniauth` dependency to version 1.3.2 or greater to satisfy vulnerability described in https://nvd.nist.gov/vuln/detail/CVE-2017-18076. We depend on `omniauth` by way of `omniauth-saml-va` by way of `omniauth-saml`. I have created a [PR in omniauth-saml](https://github.com/omniauth/omniauth-saml/pull/148) to upgrade the version that package depends on.
=> Upgrade downstream dependency on omniauth

client/src/containers/UnauthorizedContainer.jsx
Once the frontend toolkit [PR to add the StatusMessage](https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit/pull/11) is merged I will move this over to use that shared StatusMessage component instead of `<AppSegment>`.
Tested that this displays correctly by adding a route in `InitContainer` and navigating to that route. Since I think this will more usually be used as an alert (and not a page to which folks are redirected), I did not include that route in this PR. I imagine this alert will probably respond to some global state in `InitContainer` that we set off an action based on an API response.
=> Add unauthorized alert to react app

app/jobs/v2/download_manifest_job.rb, app/jobs/v2/package_files_job.rb, app/services/record_fetcher.rb
Currently in UAT eFolder errors whenever grabbing the mutex. It appears to be because we're trying to connect to redis using connection rather than url, and so are trying to connect to localhost. Trying to connect a semaphore using url works in the rails console on UAT.
**Test Plan**
```
s = Redis::Semaphore.new("TEST LOCK", url: Rails.application.secrets.redis_url_sidekiq)
s.lock(1)
s.unlock
```
=> Redis::Semaphore Changing `connection` to `url`

lib/tasks/ci.rake, lib/tasks/lint.rake, lib/tasks/sauceci.rake, lib/tasks/security.rake, lib/tasks/spec_browsers.rake
When we run rake tasks for efolder we end up running [caseflow commons' rake tasks](https://github.com/department-of-veterans-affairs/caseflow-commons/blob/6be9e1e95b1a012af1fb5b7aa292ec7123281dc2/lib/tasks/ci.rake) with the same name. One way to avoid this is to namespace the rake tasks so they don't have the same name. This should speed up efolder builds because the CI server isn't running caseflow commons tasks when all we care about is efolder express. Once consequence of this change is that in order to run any of the tasks, we need to add the namespace (e.g. `bundle exec efolder:lint`).
=> Namespace rake tasks

Gemfile, Gemfile.lock
Upgrade to the [most recent commit of connect_vbms](https://github.com/department-of-veterans-affairs/connect_vbms/commit/f014b4772385814cd510712c46698653866f99dd) which upgrades version of Nokogiri to mitigate a [known vulnerability](https://github.com/sparklemotion/nokogiri/issues/1714) with that package.
This change does not change the version of Nokogiri efolder depends on because the [similar change for ruby-bgs](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/862) was merged into master prior to this one and affected the change in Gemfile.lock.
=> Upgrade connect_vbms version

client/src/containers/DownloadContainer.jsx, client/src/containers/WelcomeContainer.jsx
Mark identified the possibility of removing a redundant API call [in a previous PR](https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/857#pullrequestreview-94419662). This PR contains the code to make that change.
=> Skip redundant API request if possible

client/src/apiActions.jsx
Connects #872.
Fixes a bug where the active tab on the download progress page would not display the correct default.
=> Set active tab on download progress page properly

client/package.json, client/yarn.lock
Move development dependencies to production dependencies so that we can build the javascript bundle as part of the deployment process (see [related PR in appeals-deployment](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1273)).
=> Support building js bundle in deployment pipeline

client/src/containers/DownloadContainer.jsx
Connects #878.
When we show an error on one of the react downloads pages, we don't show the header that contains the Veteran's name and ID. This PR changes that so we do show that information.
=> Show header when displaying error

client/package.json, client/src/components/DownloadPageHeader.jsx, client/yarn.lock
Connects #874.
Makes the copy to clipboard button work after breaking that functionality in the move to react.
=> Make copy to clipboard function work

app/services/download_documents.rb, client/src/apiActions.jsx, spec/features/download_spec.rb, spec/requests/api/v1/file_spec.rb, spec/services/download_documents_spec.rb
A number of documents were uploaded to a veteran's file that were intended for another veteran. When those files were removed from VBMS, we never remove them in eFolder. Therefore you can still view them in Reader. This isn't a problem in the new eFolder API, but we're back-porting the change to v1.
**Test Plan**
=> Removing documents from eFolder when no longer in VBMS

client/src/apiActions.jsx
The `FILE_NUMBER` header works locally but does not work in UAT (returns a "missing header: File Number" 400 error). Changed the header to `FILE-NUMBER` to match caseflow, tested locally and it works. Fingers crossed that this will work in UAT as well.
=> Change file header

Gemfile, Gemfile.lock
A [recent change](https://github.com/department-of-veterans-affairs/ruby-bgs/pull/50) to the ruby-bgs gem resolves an issue that was resulting in an uncaught NoMethodError. This change incorporates those changes from the latest version of the ruby-bgs gem.
=> Update BGS dependency

Jenkinsfile
Currently we use tags to determine the message we will send to slack when deploying efolder. There are some issues with how we automatically tag deploys right now, so the messages we send to Slack include more commits than are actually being newly deployed. Because of the [recent changes](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/1309) to appeals-deployment, efolder deploys every minute if there are any changes to master. As a result we can simplify the deploy message we display.
One downside to the change here is that we only display the most recent commit message instead of all commits that are being deployed. Since we will deploy every minute if there are changes to deploy, and since we require our CI suite to run after merging to master, and since …
=> Update message we send to slack on deploy

Gemfile, Gemfile.lock
Upgrading to most recent version of omniauth-saml-va to get [most recent version](https://rubygems.org/gems/omniauth-saml) of omniauth-saml.
Information on vulnerability here: https://www.securityweek.com/widespread-vulnerability-found-single-sign-products
=> Upgrade omniauth-saml-va dependency to mitigate vulnerability

Gemfile, Gemfile.lock, spec/jobs/download_vva_manifest_job_spec.rb
Connects #916.
Envoy is already handling these retries, and they are just all failing. With [the change to connect_vva](https://github.com/department-of-veterans-affairs/connect_vva/pull/23), we rethrow this error as a VVA::ClientError and will catch it in DownloadManifestJob. The ExceptionLogger will bypass sending this particular error to sentry, and we will set the download as errored in [DownloadAllManifestJob](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/864287fd3d818db516bb899f9dccf402ac642459/app/jobs/download_all_manifest_job.rb#L13).
=> Upgrade to latest version of connect_vva

app/models/manifest.rb
This code should prevent from creating two manifest sources with the same name and manifest ID when done at exactly the same time: 
```
[#<ManifestSource id: 110, manifest_id: 55, status: 1, name: "VVA", fetched_at: nil, created_at: "2018-03-06 08:46:21", updated_at: "2018-03-06 08:46:21">]>
#<ManifestSource id: 111, manifest_id: 55, status: 0, name: "VVA", fetched_at: nil, created_at: "2018-03-06 08:46:21", updated_at: "2018-03-06 08:46:21">
```
Should fix this Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/999/
Tested manually.
=> Add a lock when creating a manifest source

client/src/containers/DownloadContainer.jsx
Connects #910.
Fixes a bug in the original PR for that issue (#911) that made every search results page (that did not have another error message) display the "No Documents in eFolder" message. I guessing I missed this in my manual testing because I was only testing the case where the message would appear and did not attempt to test any case where it shouldn't. We don't currently have any automated tests running against the react code (coming soon thanks to #915!), but I imagine automated tests would have caught this issue.
=> Fix order of condition bug in search results page

client/src/containers/DownloadContainer.jsx, client/src/containers/DownloadListContainer.jsx
Connects #907.
Make some tweaks to the text and style of the banner we display when we have an error reaching VVA or VBMS. Result of @Chingujo's [suggestions on the original issue](https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/907#issuecomment-371291342).
=> Change text of document source error banner

client/src/containers/DownloadProgressContainer.jsx
Connects #928.
Addresses one of the nits in the "React Design Pass" issue.
=> Remove period at end of banner title

app/controllers/application_controller.rb
Prior to this change we seeded the react app with the wrong list of recent downloads (we used the `recent_downloads()` function from ApplicationController instead of the [function of the same name](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/bd04b811eef545988955db99b47bb7cef5a950e6/app/models/user.rb#L44) from the User model. This PR fixes that.
An image of the previous error we would get if the user had any recent v1 downloads:
=> Fix recent downloads list bug caused by calling wrong recent_downloads function

app/controllers/application_controller.rb, app/controllers/health_checks_controller.rb, config/routes.rb
Whenever a user visits an efolder URL that is not specified in `config/routes.rb`, they will be presented with a rails error ([example sentry error](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1022/)). This change fixes that by redirecting non-specified routes to the unauthorized page if the user does not have access to the react single page app.
Tested this by altering the code to have `can_access_react_app?()` return false and navigating to *http://localhost:3000/browserconfig.xml* (triggers rails error) before this fix, as well as after (redirects to the react version of */unauthorized* or the html templates v1 version of */unauthorized* if `can_access_react_app?()` returns false).
=> Prevent error when visiting non-specified routes

Procfile
For whatever reason, when I fired up `foreman start` for efolder this morning it had the rails server listening on port 5100. I did some quick googling (duck duck go-ing to be honest) and couldn't find any reason why this might have changed (rails 5?). Either way, I don't think there is any harm is explicitly setting which port we expect the rails server to listen on (3000).
=> Explicitly define the port for the rails server to listen on

.travis.yml, app/controllers/api/v2/manifests_controller.rb, spec/features/download_spec.rb
Connects #943.
Efolder Express UI v1's [DowloadsController](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/1284734617e65d66d2e4a4a216b80ec44c399f9b/app/controllers/downloads_controller.rb#L13) validates that an [efolder exists for a given file number](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/1284734617e65d66d2e4a4a216b80ec44c399f9b/app/models/search.rb#L73) (by way of `[Search.perform()](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/1284734617e65d66d2e4a4a216b80ec44c399f9b/app/models/search.rb#L30)`and displays a message on the [search results page](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/1284734617e65d66d2e4a4a216b80ec44c399f9b/app/views/downloads/new.html.erb#L2) if one does …
=> Return veteran efolder not found message

Gemfile, Gemfile.lock, app/controllers/api/v1/application_controller.rb, spec/requests/api/v2/manifests_spec.rb
Connects #946.
Since the caseflow application cannot do anything to resolve the "Savon::SOAPFault: (S:Client) ID: {{UUID}}: Logon ID {{CSS_ID}} Not Found" errors, we will pass along those errors to the calling client code.
This code change relies on changes in [ruby-bgs PR#51](https://github.com/department-of-veterans-affairs/ruby-bgs/pull/51).
=> Return error to calling code if error is a PublicError

Gemfile.lock
Fixes CVE-2018-8048. See the [related issue on GitHub](https://github.com/flavorjones/loofah/issues/144).
=> Address loofah dependency vulnerability

app/services/manifest_fetcher.rb
Connects #945.
Currently there are only two ManifestSources out of 638 (~0.3%) that are in this state:
```
ManifestSource.find_by_sql("select * from manifest_sources where status = 1 and created_at + interval '1 day' < current_timestamp")
```
I think we should make this change, flip these two statuses to failed, and add a cron job that looks for ManifestSources that end up in this state so we can more thoroughly investigate the cause of this issue closer to the time when it occurs.
=> Throw error if ManifestSource status update fails

app/controllers/api/v1/application_controller.rb, app/controllers/api/v1/documents_controller.rb, app/controllers/api/v1/files_controller.rb, app/controllers/api/v2/manifests_controller.rb, app/controllers/api/v2/records_controller.rb, spec/requests/api/v2/manifests_spec.rb
Added more expressive copy for sensitive records alert to match what [currently exists in efolder html](https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/3a55456ea222374c7e7ee5217ae3621d7ce5b2e7/app/views/downloads/new.html.erb#L31) templates UI. Changing this copy should have no effect on the caseflow code that depends on this response since [that code](https://github.com/department-of-veterans-affairs/caseflow/blob/db575e1162ddf169074980fc97dca1ae826a4d55/app/services/external_api/efolder_service.rb#L19) only checks the HTTP response code and not the text of the message.
=> Improve sensitive record message

app/jobs/alert_stuck_manifest_source_job.rb, config/sidekiq_cron.yml
Connects #945.
Add this cron job so we can investigate the issue of ManifestSources getting stuck in the "pending" state closer to the first occurrence of this happening when (if?!) it happens next.
Have not yet reset the two ManifestSources that are stuck in this state because I want to confirm this runs by using those two ManifestSources as our guinea pigs.
=> Add cron job to check for stuck ManifestSources

config/sidekiq_cron.yml
Connects #945.
Efolder's time zone is set to UTC, when I wrote this code I incorrectly assumed our application's time zone was set to eastern. We want this cron job to run in eastern time. This code change fixes that.
=> Explicitly set time zone in sidekiq cron job

db/migrate/20180321175540_remove_duplicate_manifests.rb, db/migrate/20180321175556_remove_manifest_index.rb, db/migrate/20180321175607_add_manifest_index.rb, db/schema.rb
We want to have a DB level validation to ensure our manifests are unique per file_number. This PR recreates the index on the Manifest table to make it unique.
**Test plan**
=> Recreating index with unique constraint

app/services/manifest_fetcher.rb, spec/services/manifest_fetcher_spec.rb
We recently added a unique constraint to the document_id field of the records table. Previously we were using rails validations. However, using unique constraints in validations doesn't guarantee uniqueness since there can be race conditions. The only way to ensure this is to put the constraint at the DB level. We also made a change to start using `create!` instead of `create` to build our records. This way we are alerted when record creations fail. Last night we began receiving a lot of this error: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1079/events/latest/. `PG::UniqueViolation: ERROR: duplicate key value violates unique constraint "index_records_on_version_id" DETAIL: Key (version_id)=({F291C1BC-FCDE-4C58-8544-B4FCE2E59008}) already exists.` Each of the …
=> Special case the VVA duplicate document id error

app/services/manifest_fetcher.rb
There appears to be another duplicate in the VVA documents. This PR exempts it for now... but this will hopefully be removed soon. Here is the plan.
Minh (VVA owner) says he is looking into the duplicates and will have answers for us on Wednesday. We'll keep adding exemptions until then to keep things usable. If they can fix the problem easily, then GREAT. We'll keep our code as is and let them fix the problem. If they cannot, then here is our backup plan:
1) Remove unique constraint on `version_id`
1) Add unique constraint to `["manifest_source_id", "version_id"]`
1) When retrieving documents from VVA only allow each `version_id` once for each manifest source id.
Still not ideal... but will probably get us through.
=> Adding another exception to VVA documents

app/views/gui/single_page_app.html.erb
We lost a meta tag in the refactor that tells IE to not render in compatibility mode. Adding it back in, seems to fix any rendering problems in IE when compatibility mode is turned on.
=> Adding meta tag to disable compatibility mode

client/src/apiActions.jsx, client/src/containers/DownloadProgressContainer.jsx, lib/tasks/spec_browsers.rake, spec/features/backend_error_flows_spec.rb
Fixes: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/976
This PR address two issues:
1) Stops the download page from always making the progress tab active whenever the list of files changes.
2) Adds a failed message when the manifest status is set to failed. This means there was some error on our end when processing the download. The user should try again or send feedback if that fails.
**Test Plan**
=> Add manifest failed page and fix active tab

app/jobs/middleware/job_data_dog_metric_middleware.rb, config/initializers/shoryuken.rb
We currently don't have metrics on how long our jobs are taking. This adds a data dog metric so we can start to analyze it.
**Test Plan**
=> Adding job length metrics

app/jobs/middleware/job_raven_reporter_middleware.rb, config/initializers/shoryuken.rb
Fixes: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/984
We lost a lot of detail in our Sentry error reporting when we move from sidekiq to SQS. This adds middleware to report the same level of detail.
**Test Plan**
=> Adding middleware to report errors correctly

app/jobs/middleware/job_sigterm_middleware.rb, app/jobs/v2/package_files_job.rb, config/initializers/shoryuken.rb
Connects: https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/975
Lots of interesting things to report about Ruby, SQS and Shoryuken.
1) Ensure blocks are run even when a process is shutting down. When shoryuken receives a SIGTERM it goes into a shutdown cycle. It somehow terminates any running jobs (I can't figure out how since I cannot seem to catch a relevant exception). But since ensure blocks still run, the locks we acquire on each job start are released.
2) Setting visibility timeout of a message to 0 allows another worker to pick it up immediately.
3) Shoryuken allows you to write middleware where you can modify the SQS visibility timeout.
Putting these altogether gives us the ability to use ensure blocks to make visibility timeouts 0 when Shoryuken is …
=> Release message after SIGTERM

app/jobs/middleware/job_sigterm_middleware.rb
It is not recommended to set visibility timeout to 0. Read here: 
https://github.com/aws/aws-sdk-js/issues/1279#issuecomment-268830676
Sentry error: https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/1190/
=> Set visibility timeout to 30 seconds instead of 0

app/jobs/v2/download_manifest_job.rb, app/jobs/v2/package_files_job.rb, app/models/manifest.rb, app/models/manifest_source.rb
Connects #995.
First half of the fix for #995 here. The ultimate fix is to offload all of the queue handling to SQS by way of Shoryuken and make extensive use of [SQS ChangeMessageVisibility](https://github.com/phstc/shoryuken/wiki/Worker-options#auto_visibility_timeout) to ensure that the job is always in process or soon to be made available on the queue.
In order to allow for that approach, we need to have jobs execute when we fire them off. The Redis/Semaphore lock could prevent that from happening (if an EC2 instance is killed while the job is running we will try to run it again when SQS makes the message available, but will run into the lock once we start executing the job). Since the lock exists to prevent us from doing the work in the job multiple times, we can move that lock out …
=> Move lock from job to model

Gemfile, Gemfile.lock
Installs a newer version of the `connect_vbms` gem - this one supports SHA256 digests, which is critical for the upgraded certs VBMS is using in their uat environment. 
(the changes in `connect_vbms`: see [connect_vbms#178](https://github.com/department-of-veterans-affairs/connect_vbms/pull/178))
This is how I've been testing out the gem from an app server:
```
require 'vbms'
client = VBMS::Client.from_env_vars(env_name: ENV["CONNECT_VBMS_ENV"], use_forward_proxy:true)
request = VBMS::Requests::FindDocumentSeriesReference.new("<id>")
res = client.send_request(request)
```
Before the fix, we had been observing 503s on uat. After deploying this fix, we are seeing success responses.
=> upgrades connect_vbms version to support SHA256

db/migrate/20180516212947_add_user_id_index_to_files_download.rb, db/schema.rb
One possible solution to the increased load on efolder's database is to add an index on the user_id column of files_download since we lookup by that column very frequently and the query that looks up by that column is a big problem child. Extended discussion in slack https://dsva.slack.com/files/U7GARLGMB/FAQSJNS0L/image.png
=> Add user_id index on files_downloads table

app/models/manifest.rb, spec/features/react_download_spec.rb
Connects to #1010 
Find a Manifest that was downloaded before more than 2 weeks ago. 
Try to search for that file number (as a different user who downloaded it initially).  
You should get a page where you have to retrieve efolder instead of download efolder.
=> Fix reset stale manifest

app/services/document_creator.rb
If a download manifest job is run twice simultaneously (as can happen with SQS at least once delivery) we can get a race condition where we try to create records in a transaction that have already been created. In this case it should be safe to catch the error, as the other thread that won the race should have already written the records.
=> In race condition rescue ActiveRecord::RecordNotUnique

app/models/manifest.rb
Related to the `Caseflow::Error::ClientRequestError` we are seeing when Caseflow makes a request to `GET /api/v2/manifests/#{manifest_id}`: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1539/
On the caseflow side, we attempt to get a list of documents for some Veteran by making a request to `POST /api/v2/manifests` (with the Veteran ID in the request headers). We then poll the `GET /api/v2/manifests/#{manifest_id}` endpoint to determine if we have finished fetching the manifest from VVA/VBMS. In this case we failed to create both Manifest and FilesDownload records in `Manifest.find_or_create_by_user()` and the subsequent call to `ManifestsController.progress()` appropriately returned a 400.
The manifest-related actions available through the API rely on the …
=> Die if attempt to create FilesDownload object fails

client/package.json, client/yarn.lock
Reduces the chance of a security vulnerability in case someone access our NPM tokens.
=> Include packages via github not npm

README.md, app/controllers/application_controller.rb, app/controllers/sessions_controller.rb, config/environments/development.rb
Connects https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1029
- Check out the master branch and start the app connected to Redis as the cache 
- Log out
- Run `Rails.cache.write("out_of_service", true)`
- Attempt to log in
- Log in will fail
- Check out this branch
- Attempt to log in
- User will be successfully logged in, and "Technical Difficulties" page will be displayed
=> Doesn't prevent login when app is out of service

Gemfile, Gemfile.lock
Connects https://github.com/department-of-veterans-affairs/connect_vbms/pull/197
Bumps the connect_vbms gem to [08735e11](https://github.com/department-of-veterans-affairs/connect_vbms/commit/08735e11cd9fc196c8f889093580b9054fd2f094). 
This version allows an empty value for the `CONNECT_VBMS_KEYPASS` environment variable. This is an approach for dealing with the certificate update VBMS has been rolling out across its environments; while some use a key password, the preprod cert package does not use a key password (equivalent to an empty string). 
1. Deploy branch to preprod.
Jenkins settings:
- branch: `refs/heads/lisac/vbms-preprod-cert-update`
- env variables:
`APP_VERSION=lisac/vbms-preprod-cert-update`
`DEPLOY_BRANCH=lisac/vbms-preprod-cert-upgrade`
2. Get sample VBMS file numbers …
=> Update connect_vbms for change to preprod certificate

Gemfile.lock
To test: 
`bundle exec rake security`
it should pass with `Passed. No obvious security vulnerabilities.`
=> Update ffi gem due to security vulnerability

app/controllers/application_controller.rb
Connects to #1045 
department-of-veterans-affairs/appeals-support#3189
department-of-veterans-affairs/appeals-support#3192
To test locally: 
1. Seed local database with 50 "recent" manifests and around 50 records for each manifest/manifest sources.
2. Load the home page logged in as the same user from step 1. 
3. Home page should load relatively quickly
4. Make sure `ManifestSource Load` does NOT show up in server log
=> Exclude serialization of manifest sources and records when requesting home page

app/views/layouts/application.html.erb
This change will request that Google mask the last octet of the IP address in memory before performing further processing.
https://support.google.com/analytics/answer/2763052?hl=en
=> [Privacy] Anonymize IP address in Google Analytics

app/controllers/application_controller.rb
Connected to #1042 
To test:
1. Run app in dev environment
2. Search for 'DEMO1' and download file
3. Restart the server, clear the cookies and login as the same user from steps 1 and 2
4. Make sure recent download shows on home page
5. Make sure server log does not show loading of FilesDownloads as part of DownloadsController#new step
=> Remove recentDownloads from initial react data

app/jobs/v2/download_manifest_job.rb, app/models/manifest_source.rb, app/services/external_api/bgs_service.rb, app/services/external_api/vbms_service.rb, spec/jobs/v2/download_manifest_job_spec.rb
Connects to #1052 
When calling BGS service from DownloadManifestJob active job, RequestStore[:current_user] is not available since it's stored only within the main process. This PR fixes that.
To test:
Run app locally connected to external dependencies.
Search for record that has C file claim number by ssn number and make sure it returns VBMS document list.
=> Make current user info available to DownloadManifestJob

Gemfile, Gemfile.lock, app/controllers/api/v2/manifests_controller.rb, app/services/external_api/bgs_service.rb, app/services/external_api/vbms_service.rb, lib/fakes/bgs_service.rb, spec/features/backend_error_flows_spec.rb, spec/features/react_download_spec.rb, spec/features/user_error_flows_spec.rb, spec/requests/api/v2/manifests_spec.rb, spec/services/bgs_service_spec.rb
This commit broke production hence revert. 
Reverts department-of-veterans-affairs/caseflow-efolder#1060
=> Revert "Always use claim number as file_number... and other fixes"

app/controllers/api/v2/manifests_controller.rb, spec/features/user_error_flows_spec.rb
Connected to #1064 
To test this, run app locally connected to external dependencies and search for arbitrary file number. 
To ease the pain:
On VA network (VPN)
cd ~/workspace/caseflow-efolder
git checkout nemo/poa-error
git cherry-pick bb35873c14a69a97720aa525061524df9e922760
source ~/workspace/appeals-deployment/decrypted/prod/env.sh
RAILS_ENV=staging bundle exec rails s 
(in another tab)
cd caseflow-efolder
source ~/workspace/appeals-deployment/decrypted/prod/env.sh
RAILS_ENV=staging bundle exec shoryuken start -q efolder_staging_high_priority efolder_staging_low_priority efolder_staging_med_priority -R
Docker and webpack should be running as well. 
Make sure you login with the right css_id and station_id (or change current user configuration for external services)
=> Catch POA access error, return error message and add spec test

Gemfile, Gemfile.lock
Update connect VBMS version with the latest changes
1. VBMS old service endpoints were removed
Testing:
Tested efolder in UAT
See: https://github.com/department-of-veterans-affairs/connect_vbms/pull/212
=> Update connect vbms - VBMS old service is removed

app/models/manifest.rb, db/migrate/20190307025848_remove_index_files_downloads_on_manifest_id_and_user_id.rb, db/migrate/20190307034524_add_index_to_files_downloads.rb, db/schema.rb, spec/requests/api/v2/manifests_spec.rb
Reverts department-of-veterans-affairs/caseflow-efolder#1068
It turns out that FilesDownload table has already duplicate errors on manifest_id and user_id.
=> Revert "Fix not unique error on find_or_create manifest and retry"

db/migrate/20190315173947_remove_index_files_downloads_on_manifest_id_and_user_id.rb, db/migrate/20190315190057_add_index_to_files_downloads.rb, db/schema.rb, spec/requests/api/v2/manifests_spec.rb
This PR enforces uniqueness on manifest_id and user_id index. 
Merging of this change (https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/1068/files) failed (http://appealsjenkins.ds.va.gov/job/deploys/job/prod/job/efolder/2/console) since there was duplicate data existing in database. This PR was created in accordance with redundancy cleanup in parallel.
=> Make files_downloads index with unique constraint

client/src/containers/InitContainer.jsx, client/src/containers/RecentDownloadsContainer.jsx, client/src/containers/WelcomeContainer.jsx, spec/features/backend_error_flows_spec.rb, spec/features/react_download_spec.rb
On home page load - Before: 
On home page load - After:
=>  Move recent downloads to a separate page

Gemfile, Gemfile.lock
```Name: nokogiri
Version: 1.8.5
Advisory: CVE-2019-11068
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/issues/1892
Title: Nokogiri gem, via libxslt, is affected by improper access control vulnerability
Solution: upgrade to >= 1.10.3```
=> Update bgs (and nokogiri)

app/services/external_api/bgs_service.rb
We changed the method name in #1082 and missed this one.
=> Fix method name regression

Gemfile, Gemfile.lock, app/exceptions/dependency_error.rb
Our string matching expects the original exception class name to match against.
=> Include exception class name in matching message string

docker-compose.yml
To run side-by-side with caseflow, we need the range of localstack ports in efolder to be 14561-14583 and map to 4561-4583 internally on the docker instance.
=> fix localstack ports for sqs development

.gitignore, Gemfile, Gemfile.lock, README.md, app/controllers/api/v2/manifests_controller.rb, app/models/files_download.rb, config/database.yml, db/migrate/20190506184440_add_indexes_to_manifest_read.rb, db/schema.rb, spec/models/files_downloads_spec.rb, spec/requests/api/v2/manifests_spec.rb
This PR does a few things to help speed up often-accessed API endpoints:
* Read from the db replicant rather than db master, where appropriate
* Adds index to manifest_sources and files_downloads.
* Refactors some controller methods into the model to make it easier to test and profile.
=> Distribute reads, add indices

app/controllers/application_controller.rb, client/src/containers/FeedbackContainer.jsx, client/src/containers/InitContainer.jsx, config/environments/development.rb, config/environments/staging.rb, config/environments/test.rb, spec/features/send_feedback_spec.rb
**Merge date should be on/after May 13.** 
Resolves https://github.com/department-of-veterans-affairs/caseflow/issues/10257
This PR creates Feedback page with status message. Make sure https://github.com/department-of-veterans-affairs/caseflow-frontend-toolkit/pull/50 is merged first before merging (and caseflow-frontend-toolkit version reference updated). 
- Any 'Send feedback' link in Caseflow app should take to this page
1. Go to any page and click 'Send feedback', it should show status message
=> Add feedback page, remove env var for feedback and fix spec test

app/controllers/api/v2/manifests_controller.rb, app/services/document_counter.rb, app/services/document_creator.rb, app/services/document_filter.rb, app/services/download_documents.rb, app/services/manifest_fetcher.rb, config/routes.rb, spec/rails_helper.rb, spec/requests/api/v2/manifests_spec.rb, spec/services/document_counter_spec.rb, spec/services/document_creator_spec.rb
**Why**: Caseflow Queue needs only a document count for display purposes. We should not have to wait for the entire manifest's worth of documents to be downloaded and processed if all we need is the count that will eventually be downloaded.
This API endpoint should provide a very fast count of what the manifest will eventually contain.
=> Add DocumentCounter service and controller endpoint

app/controllers/api/v2/application_controller.rb, app/controllers/api/v2/files_downloads_controller.rb, app/controllers/api/v2/manifests_controller.rb, app/controllers/api/v2/records_controller.rb, app/controllers/api/v2/veterans_controller.rb, app/services/document_counter.rb, app/services/external_api/vbms_service.rb, app/services/external_api/vva_service.rb, config/routes.rb, lib/fakes/document_service.rb, spec/requests/api/v2/manifests_spec.rb, spec/requests/api/v2/veterans_spec.rb, spec/services/document_counter_spec.rb
**Description**
Adds a new API endpoint `GET /api/v2/veterans` which will return the document count for the Veteran.
**Why**
No manifest required. Returns the total documents across all services for any Veteran.
=> DocumentCounter can use Veteran or Manifest

Gemfile, Gemfile.lock
Should quiet slack alerts for non-actionable HTTP errors.
=> BGS::TransientError version

Gemfile, Gemfile.lock, README.md, config/environments/development.rb, config/environments/staging.rb, config/secrets.yml
* Removing sidekiq env variables as we no longer use sidekiq.
* Removing metrics password/username since these were used by Prometheus
Test plan:
=> Remove unused env vars

app/models/manifest.rb, app/models/manifest_source.rb, app/services/record_fetcher.rb, config/environments/development.rb, config/environments/staging.rb, config/secrets.yml
1. Remove metrics env vars since we are longer using Prometheus
2. Move Redis semaphore to use the same Redis cache url as the rest of the app 
To test:
=> Remove unused env vars and make sure semaphore uses Redis cache

.circleci/config.yml, .rspec, Makefile.example, lib/tasks/ci.rake
CircleCI config only.
Breaks out lint and security steps from tests, and uses Makefile.example to verify we have targets defined correctly.
=> Make CI steps separate to make lint failures more obvious

.rubocop.yml
I found this 7 year old thread in the [Ruby style guide](https://github.com/rubocop-hq/ruby-style-guide/issues/76) about this and though the Ruby community isn't necessarily fully on board, there seems to be healthy debate. I'm proposing disabling this rule anyways in order to preserve the blame on that line, and because it's a widely accepted practice outside of Ruby (what most of this team is used to).
=> Disable trailing comma in literal lint rule

Makefile.example
New deployment code assumes a `make etl-migrate db-migrate` set of targets.
Those targets are Caseflow-specific, so these stubs just create parity.
=> parity with Caseflow migrate targets

app/services/document_counter.rb, spec/services/document_counter_spec.rb
connects #1191 
DocumentFilter was applied but not `uniq` on document_id.
Tested in production via console monkey patch.
=> Fix doc count

app/services/document_counter.rb, app/services/external_api/bgs_service.rb, app/services/manifest_fetcher.rb, app/services/veteran_finder.rb, spec/requests/api/v2/document_counts_spec.rb, spec/requests/api/v2/manifests_spec.rb, spec/services/document_counter_spec.rb, spec/services/veteran_finder_spec.rb
Follow on to #1188 and #1192 
Apply the same multiple-file-numbers logic to getting document count.
Tested in production with monkeypatch console on same details as #1137
=> Apply VeteranFinder to DocumentCounter

app/services/veteran_finder.rb
BGS does not always have all the expected numbers. Log them in Sentry until we can determine which patterns are worth ignoring and which require code fixes.
=> Veteran Finder reports missing data

app/services/veteran_finder.rb, spec/services/veteran_finder_spec.rb
Stop logging to Sentry since this is a common enough, non-actionable scenario.
=> BGS often missing :file_number, so not an error

.circleci/config.yml, app/services/external_api/bgs_service.rb, lib/fakes/bgs_service.rb, spec/requests/api/v2/manifests_spec.rb, spec/services/bgs_service_spec.rb
e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/8396/
Fixes VBMS::FilenumberDoesNotExist -- we were trusting too much in the preflight BGS return message value.
connects https://github.com/department-of-veterans-affairs/caseflow/issues/10732 and https://github.com/department-of-veterans-affairs/caseflow/issues/6680
This PR also adds local support for testing. If the file number supplied starts with `404` then it can be tested for "validity" as well as "not found".
=> Verify veteran_info for "not found", do not rely only on BGS return_message

app/services/bgs_service.rb, app/services/veteran_finder.rb, lib/fakes/bgs_service.rb
Fixes 2 regressions found in recent changes to how we initialize BGSService and how we de-duplicate Veteran records.
=> Fix regressions in bgs client and veteran de-duping

app/models/user.rb
Configure static system user accounts for admin maintenance. These are identical to the settings in Caseflow since they are used by VBMS/BGS.
Common usage in AWS env:
```
irb> RequestStore[:current_user] = User.system_user
```
=> Add User.system_user

app/services/external_api/vva_service.rb
Caching at the class level means app must be restarted to change config.
=> Do not cache VVA client as class object

app/models/css_authentication_session.rb, app/models/user.rb, app/services/bgs_service.rb, app/services/concerns/poa_mapper.rb, app/services/external_api/bgs_service.rb, app/services/manifest_fetcher.rb, config/initializers/bgs.rb, db/migrate/20200504163452_add_user_participant_id.rb, db/schema.rb, lib/fakes/bgs_service.rb, spec/services/bgs_service_spec.rb
connects #1218 
* Add BGS service endpoints for PID and Person services. This will allow us to begin implementing POA rules based on the same endpoints that Caseflow uses.
* Add `participant_id` to the `User` model so we can look up POA matches more easily for the `current_user`.
* Start re-orienting the authorization model to check permissions at the boundaries for BGS calls.
=> Power of Attorney rules (part 1)

app/services/record_fetcher.rb
Adding safe navigation to silence these [Sentry](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/6906/) [alerts](https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/8277/) caused by an exception when creating the semaphore.
As far as I can tell, this happens when deploying/destroying efolder, and is pretty benign.
=> Prevent exception after semaphore failure

app/models/manifest.rb, app/models/record.rb, app/models/veteran.rb, app/services/user_authorizer.rb, spec/requests/api/v2/manifests_spec.rb
Previously we were applying user authorization at the controller level for initial request, but the serialization level makes a subsequent call to BGS which was not getting the same authorization rules applied.
=> Apply per-user authorization at the Veteran model level

app/services/concerns/poa_mapper.rb, app/services/external_api/bgs_service.rb, app/services/pdf_service.rb, app/services/user_authorizer.rb, app/services/zipfile_creator.rb, lib/fakes/bgs_service.rb, spec/controllers/api_v2_application_controller_spec.rb, spec/requests/api/v2/manifests_spec.rb, spec/services/user_authorizer_spec.rb
We were missing one key piece in the user authorization logic model, which is that the PID of the user is not the same PID referenced by the bgs.claimants POA responses. As the field name suggests the BGS response has `person_org_ptcpnt_id` which means we must look up the `org` participant id and use that to compare.
=> Use the POA org pid to compare, not the POA user pid

app/controllers/application_controller.rb
Removing v1 code revealed that authorization checks were not being applied in react-land.
=> No authorization needed for home page (authn only)

db/migrate/20200526162945_user_css_id_unique.rb, db/schema.rb, spec/features/react_download_spec.rb
connects #1135 
CSS_ID is now enforced to be unique. See https://github.com/department-of-veterans-affairs/caseflow/pull/10188
`last_login_at` added for performance.
All duplicate CSS_ID records have been resolved in production.
=> Add user table indices

app/services/manifest_fetcher.rb
https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/8396/events/e25bd75fe3e04e6b9fe28c2dcb54463d/
If there are multiple file numbers, do not throw an exception if only one of them fails to be found.
=> Avoid VBMS::FilenumberDoesNotExist unless we match zero file numbers

app/controllers/application_controller.rb, spec/controllers/application_controller_spec.rb
IDT login flow assumes that a plain text MIME request will return 200 with a cookie. When we removed the v1 code, that stopped working.
This change returns a 200 response for GET requests to the root path for HTML, text and JSON, even if only HTML is actually supported.
See https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/10462/events/02e96652a7ee4918840084810635d350/
=> Handle text and json requests in SPA root

app/services/record_fetcher.rb
Method `content_from_vbms` seems to be able to retrieve document content from VVA as well, so rename method to avoid confusion.
=> Rename content_from_vbms to avoid confusion

app/controllers/api/v2/application_controller.rb, app/models/veteran.rb, spec/controllers/api_v2_application_controller_spec.rb, spec/features/user_error_flows_spec.rb, spec/requests/api/v2/manifests_spec.rb
connects #1218 
Removes the `user_authorizer` feature toggle now that it has been running for [all users in production](https://github.com/department-of-veterans-affairs/appeals-deployment/pull/2740) for a couple weeks.
=> Remove user_authorizer feature toggle

app/controllers/api/v2/files_downloads_controller.rb
See: 
* https://github.com/rack/rack/issues/1619
* https://github.com/rack/rack/issues/1628
Resolves a bug introduced in rack `2.2.2` with streaming data. The fix disables the `Rack::ETag` middleware for the downloads route to prevent it from buffering the S3 data before sending it to the client.
To reproduce, edit `app/controllers/api/v2/files_downloads_controller.rb`:
1. Disable the manifest check
```ruby
#before_action :files_download_exists?
```
2. Stream dummy data back over 60 seconds
```ruby
def zip
streaming_headers
self.response_body = Enumerator.new do |y|
(0..60).each do
y << 'test'
sleep 1
end
end
end
```
3. Remove headers that rely on the manifest
```ruby
def streaming_headers
headers["Content-Type"] = "application/zip"
headers["Content-disposition"] = "attachment; …
```
=> Workaround for rack 2.2.2 streaming bug

app/services/user_authorizer.rb
The `ExternalApi::BGSService.fetch_claims_for_file_number` method may return a single `Hash`, or an `Array` of hashes. This PR fixes a bug where a single returned `Hash` was being split into an array of all its keys & values rather than converted into an array containing a single hash, as intended.
given:
```ruby
hash_input = {one: "one", two: "two", three: "three"}
array_input = [{one: "one", two: "two", three: "three"}, {four: "four", five: "five", six: "six"}]
```
before:
```ruby
Array(array_input).flatten
=> [{:one=>"one", :two=>"two", :three=>"three"}, {:four=>"four", :five=>"five", :six=>"six"}] # good!
Array(hash_input).flatten
=> [:one, "one", :two, "two", :three, "three"] # bad!
```
after:
```ruby
[array_input].flatten
=> [{:one=>"one", :two=>"two", :three=>"three"}, …
```
=> correctly handle return of a single hash when fetching claims

db/migrate/20201201160251_change_record_id_to_bigint.rb, db/schema.rb
We are currently at over the int limit for Record ids. This bumps us to bigints (2147483647 limit to 9223372036854775807)
`make migrate` succeeds
`bin/rails db:rollback` succeeds
after migrating:
```ruby
pp Record.columns.first
#<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x00007fcbb27b39c0
@collation=nil,
@comment=nil,
@default=nil,
@default_function="nextval('records_id_seq'::regclass)",
@max_identifier_length=63,
@name="id",
@null=false,
@sql_type_metadata=
#<ActiveRecord::ConnectionAdapters::SqlTypeMetadata:0x00007fcbb27b3ad8
@limit=8,
@precision=nil,
@scale=nil,
@sql_type="bigint",
@type=:integer>,
@table_name="records">
manifest = Manifest.create(file_number: "1234")
source = ManifestSource.create(name: %w[VBMS VVA].sample, manifest: manifest)
Record.create(id: 2147483283, …
```
=> Bigint for record ids

app/models/record.rb, db/migrate/20201201174552_add_temp_id_to_records.rb, db/migrate/20201201181531_add_index_to_temp_id.rb, db/schema.rb, spec/models/record_spec.rb
Added a column to store id in big int as part one in: https://jilt.com/blog/migrations-zero-downtime-rails/
all the below succeed
```bash
$ make migrate
...
[2020-12-01 13:18:42 -0500] Migrating to AddTempIdToRecords (20201201174552)
[2020-12-01 13:18:42 -0500]    (2.7ms)  BEGIN
== 20201201174552 AddTempIdToRecords: migrating ===============================
-- add_column(:records, :temp_id, :bigint)
[2020-12-01 13:18:42 -0500]    (2.7ms)  ALTER TABLE "records" ADD "temp_id" bigint
-> 0.0032s
== 20201201174552 AddTempIdToRecords: migrated (0.0034s) ======================
[2020-12-01 13:18:42 -0500]   ActiveRecord::SchemaMigration Create (3.2ms)  INSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"  [["version", "20201201174552"]]
[2020-12-01 13:18:42 -0500] …
```
=> Store id in temp binint column

.github/workflows/build.yml
Editing a PR should not trigger the workflow, especially not until new workflows cancel previous ones that are not longer needed.
=> Remove editing PR from list of trigger

app/services/slack_service.rb, config/initializers/deprecation_warning_subscriber.rb, spec/initializers/deprecation_warning_subscriber_spec.rb, spec/services/slack_service_spec.rb
(Re-)Resolves: https://jira.devops.va.gov/browse/APPEALS-26715
This reverts commit 86b473747f65efaf785d0c18dc8f76f066aad5ae, which accidentally wiped out the changes from original PR https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/1402 when it was merged into `master`.
See https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/1402 for more details.
=> AlecK/APPEALS-26715 Setup monitoring for deprecation warnings (again)

.github/workflows/build.yml, docker-compose-local.yml, docker-compose-m1.yml, docker-compose.yml
Resolves [APPEALS-35629](https://jira.devops.va.gov/browse/APPEALS-35629)
Upgrade the `postgres` image versions from 11.7 to 14.8.
1. Go to [APPEALS-35629](https://jira.devops.va.gov/browse/APPEALS-35629) and note the attached tests.
=> MattT/APPEALS-35629: Upgrade Docker Image Versions in docker-compose and GHA Workflow Files

.github/workflows/build.yml, spec/features/help_spec.rb
Resolves [APPEALS-37215](https://jira.devops.va.gov/browse/APPEALS-37215)
Alters the build GHA workflow to execute the RSpec command within a bash shell with pipefail enabled so that error codes thrown by test failures aren't eaten by our output redirection.
1. Verify that the RSpec step in [this CI execution](https://github.com/department-of-veterans-affairs/caseflow-efolder/actions/runs/7283418631/job/19847258013) failed appropriately due to an intentional test failure.
2. Ensure that the artifact upload steps **did** execute, uploading test logs and Capybara snapshots.
3. A download link for an artifact.zip file should be on the [summary page](https://github.com/department-of-veterans-affairs/caseflow-efolder/actions/runs/7283418631) that contains the aforementioned artifacts.
4. Make …
=> Ensure Errors From RSpec Test Failures Register in GHA Workflows

app/controllers/api/v2/records_controller.rb, config/application.rb, spec/requests/api/v2/records_spec.rb
Resolves Backend for APPEALS-39777
Documents V2 API #show, add new header key X-Document-Source that will show "VBMS" or "S3".
The Caseflow-Reader app uses this API to show documents and will track if the document was sourced from AWS S3 or VBMS to see if there is a correlation with the response time. 
1. Go to ...
BEFORE|AFTER
---|---
=> add document source to records api v2 response headers

app/jobs/v2/download_manifest_job.rb, app/services/external_api/vbms_service.rb, spec/services/external_api/vbms_service_spec.rb
Resolves bug found in eFolder testing.
- Update `app/services/external_api/vbms_service.rb` to init a VBMS client automatically vs. requiring consumers to init the client themselves.
1. Run specs for changed files:
- `bundle exec rspec spec/services/external_api/vbms_service_spec.rb`
=> Fix Bug Preventing File Fetching

Gemfile.lock, app/services/json_api_response_adapter.rb, client/src/Utils.jsx, spec/services/json_api_response_adapter_spec.rb
- Add curly braces expected by code depending on the SOAP response.
- Update ruby_claim_evidence_api gem version to bugfix version.
- Revert display date fix causing issues with old functionality.
1. Run specs for changed files
=> Fix Misc. Issues with JSON API Response Handling

app/services/json_api_response_adapter.rb, spec/services/json_api_response_adapter_spec.rb
Resolves [Difference between Rest API and Soap API Date forma](https://jira.devops.va.gov/browse/APPEALS-46996)
- Use slashes instead of hyphens to help JS correctly parse the date.
1. Run specs for changed files:
- `bundle exec rspec spec/services/json_api_response_adapter_spec.rb`
=> Update received_at Date Parsing Logic

app/services/json_api_response_adapter.rb, spec/services/json_api_response_adapter_spec.rb
Improves handling of blank API responses in the `JsonApiResponseAdapter`.
1. Run specs: `bundle exec rspec spec/services/json_api_response_adapter_spec.rb`
=> Correctly Handle Blank JSON Responses

app/controllers/api/v2/records_controller.rb, app/models/record.rb, app/services/record_api_fetcher.rb, app/services/record_fetcher.rb, app/services/record_fetcher_base.rb, spec/requests/api/v2/records_spec.rb
Resolves APPEALS-46702
When Reader make an API call to eFolder to retrieve a document and document not found in the s3 cache, the eFolder will return the document directly from VBMS instead of first trying to store to s3. There is already another process that will store the document to s3
1. Go to ...
BEFORE|AFTER
---|---
=> add missing binwriter from record_fetcher

app/controllers/api/v2/records_controller.rb, app/models/record.rb, app/services/record_api_fetcher.rb, app/services/record_fetcher.rb, app/services/record_fetcher_base.rb, spec/requests/api/v2/records_spec.rb
Release R2.1.0 FY24Q4.1.0
When Reader make an API call to eFolder to retrieve a document and document not found in the s3 cache, the eFolder will return the document directly from VBMS instead of first trying to store to s3. There is already another process that will store the document to s3. 
Resolves APPEALS-46700
1. Go to ...
BEFORE|AFTER
---|---
=> Resolves APPEALS-46700 (#1647)

.github/workflows/build.yml, .github/workflows/ecr-login.yml, .github/workflows/ecr_password_updater.py
Resolves [APPEALS-53151](https://jira.devops.va.gov/browse/APPEALS-53151)
- Alters ECR Token Refresh workflow to instead utilize the OIDC flow in order to obtain temporary AWS credentials.
- Shifts all references to ECR images to instead utilize our VAEC account number.
Please see https://github.com/department-of-veterans-affairs/caseflow/pull/22348 to see these changes in action in that repository. Unfortunately, the version of the workflow in this repo didn't have the `workflow_dispatch` trigger and so it cannot be tested here until it is merged.
=> APPEALS-53151: Update ECR workflow to utilize OIDC flow

app/services/external_api/vbms_service.rb, spec/services/external_api/vbms_service_spec.rb
Resolves [APPEALS-47113](https://jira.devops.va.gov/browse/APPEALS-47113)
Validate user access to veteran before allowing fetch of veteran data.
Covers the following methods:
- FindDocumentVersionReferenceByDateRange
- FindDocumentVersionReference
- PagedDocuments
- GetDocumentContent
1. Enable feature toggle in the Rails console: `FeatureToggle.enable!(:check_user_sensitivity)`
2. In the Efolder UI, type a veteran file number and click "Search".
3. You should receive a banner stating that you need additional permissions to view this information.
=> Gate VBMS Methods with Sensitivity Checks

app/controllers/api/v2/manifests_controller.rb, app/exceptions/bgs_errors.rb, app/models/manifest.rb, app/models/manifest_source.rb, client/src/components/AlertBanner.jsx, client/src/containers/WelcomeContainer.jsx, spec/models/manifest_spec.rb
Resolves [APPEALS-47113](https://jira.devops.va.gov/browse/APPEALS-47113)
Remove checks as they are already handled by the sensitive_record method.
1. Enable feature toggle in the Rails console: `FeatureToggle.enable!(:check_user_sensitivity)`
2. In the Efolder UI, type a veteran file number and click "Search".
3. You should receive a banner stating that you need additional permissions to view this information.
=> Remove Unneeded Sensitivity Checks

.rubocop.yml, Gemfile, Gemfile.lock, Rakefile
Resolves [APPEALS-54878](https://jira.devops.va.gov/browse/APPEALS-54878)
- Update PG gem to minimum version 1.5.7
- Update rubocop to version 0.83 to resolve a dependency issue
- Remove therubyracer gem
1. Verify that automated test suite is passing
=> Update PG, rubocop gems, remove therubyracer

app/controllers/api/v1/application_controller.rb, app/controllers/api/v2/manifests_controller.rb, app/controllers/base_controller.rb, app/models/manifest.rb, app/services/sensitivity_checker.rb, spec/requests/api/v2/manifests_spec.rb
Resolves [eFolder>>View Result link on Recent Downloads throwing error page](https://jira.devops.va.gov/browse/APPEALS-57091).
For the `refresh` action in `app/controllers/api/v2/manifests_controller.rb`, the app was using `Manifest.find` to load the manifest. However, this would result in the `manifest` not having a `user` set and this was causing the new user sensitivity checks to fail.
This PR updates the `refresh` action in `app/controllers/api/v2/manifests_controller.rb` to use the `Manifest.find_or_create_by_user` method which will set `manifest.user` as part of its logic.
NOTE: UAT only
Follow repro steps in ticket and verify the issue is fixed.
=> Fix Missing Manifest User Causing Sensitivity Check Failures

app/services/external_api/vbms_service.rb, app/services/json_api_response_adapter.rb, spec/services/external_api/vbms_service_spec.rb, spec/services/json_api_response_adapter_spec.rb
Resolves [NoMethodError - undefined method `body' for Hash:0x00007f62dbafe908](https://jira.devops.va.gov/browse/APPEALS-57787)
- Gem now returns the JSON body of a HTTP response, so our response parsing code needed to be updated to handle the new format.
- Update the VBMS service to alert us of any API responses that can't be parsed so we can troubleshoot them.
1. Follow steps in ticket in UAT.
=> Update JSON Parsing Logic to Handle CE API Gem Changes

app/helpers/application_helper.rb, app/jobs/v2/download_manifest_job.rb, app/jobs/v2/save_files_in_s3_job.rb, app/services/external_api/vbms_service.rb
Resolves [NoMethodError: undefined method `css_id' for nil:NilClass](https://jira.devops.va.gov/browse/APPEALS-58178).
- Since the SaveFilesInS3 job is spawned by another job, it does not have access to RequestStore[:current_user] which is needed for verifying veteran/user sensitivity compatibility.
- This PR also fixes several Rubocop violations in various files.
1. Go to eFolder UAT.
2. Search for a veteran.
3. Verify eFolder can be fetched and download.
4. Verify there are no errors in Sentry.
=> Add current_user to SaveFilesInS3 Job

lib/scripts/find_valid_veteran_file_numbers.rb
Resolves [Veteran IDs for UAT test scenarios](https://jira.devops.va.gov/browse/APPEALS-58216)
Fixes incorrect Ruby keyword in script.
1. Run the script via the Rails console:
```
s = FindValidVeteranFileNumbers.new
s.run
```
=> Fix Incorrect Keyword in Script

app/services/json_api_response_adapter.rb, spec/services/json_api_response_adapter_spec.rb, spec/support/api_responses/ce_api_folders_files_search_unknown.json
Resolves [https://jira.devops.va.gov/browse/APPEALS-58827](https://jira.devops.va.gov/browse/APPEALS-58827)
Updated JsonApiResponseAdapter.rb file to properly use VBMS document type description from Caseflow::DocumentTypes::TYPES mapping instead of "Subject"
Updated rspecs to cover changes to this Record field
1. See [https://jira.devops.va.gov/browse/APPEALS-58827](https://jira.devops.va.gov/browse/APPEALS-58827)
2. Login to Efolder with a user of sensitivity level 9 and search up 314159004
3. Document names shown in the first column should correlate to "Category - Type" in VBMS.
4. For files not mapped in Caseflow, we should see UNKNOWN
=> Kev ma/appeals 58827 v2

app/services/external_api/bgs_service.rb
1. Go to ...
BEFORE|AFTER
---|---
=> Fix for fetch_sensitivity_level
